import { useState, useMemo, useEffect, useDeferredValue } from 'react';
import { api, fmt, reportClientError } from '../api.js';
import { useViewData } from '../useViewData.js';
import { invalidate } from '../cache.js';
import Modal from '../components/Modal.jsx';
import SearchableSelect from '../components/SearchableSelect.jsx';
import QuickAddUser from '../components/QuickAddUser.jsx';
import RowActions from '../components/RowActions.jsx';
import QueueStatus from '../components/QueueStatus.jsx';

import { canAddView } from '../permissions.js';
import { useDropdownList } from '../useDropdownList.js';
import { isTruthyFlag } from '../flags.js';

function autoGenerateDocType(payload) {
  if (payload['Is Resell'] === 'TRUE') return null;
  const type = payload['Contribution Type'];
  if (type === '1') return 'receipt';
  if (type === '2') return 'samaan';
  if (type === '3') return payload['Certificate Or Receipt'] === 'Certificate' ? 'certificate' : 'receipt_work';
  return null;
}

export default function Home({ year, users, onUserCreated, role, editable }) {

  const { data, loading, error, refresh } = useViewData(`home:${year}`, () => api.getHome(year), [year]);
  const { options: paymentModeOptions, hindiOf: paymentModeHindiOf } = useDropdownList('Payment Mode');
  const [search, setSearch] = useState('');
  const [showAdd, setShowAdd] = useState(false);
  const [showQuickAdd, setShowQuickAdd] = useState(false);
  const [form, setForm] = useState({
    Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
    Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
    Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
  });
  const [saving, setSaving] = useState(false);
  const [savingStep, setSavingStep] = useState('');
  const [postSaveWarning, setPostSaveWarning] = useState('');
  const [queueBump, setQueueBump] = useState(0);
  const [editing, setEditing] = useState(null);
  const [history, setHistory] = useState(null);
  const [historyLoading, setHistoryLoading] = useState(false);

  const userMap = useMemo(() => {
    const m = {};
    (users || []).forEach(u => { m[u.ID] = u; });
    return m;
  }, [users]);

  const userOptions = useMemo(() => (users || []).map(u => ({ value: u.ID, label: u.Name, sub: u.Village })), [users]);

  useEffect(() => {
    if (!form.Name) { setHistory(null); return; }
    setHistoryLoading(true);
    api.getUserHistory(form.Name).then(setHistory).catch(() => setHistory(null)).finally(() => setHistoryLoading(false));
  }, [form.Name]);

  const deferredSearch = useDeferredValue(search);
  const filtered = useMemo(() => {
    const q = deferredSearch.toLowerCase();
    return (data?.collections || []).filter(r => {
      if (isTruthyFlag(r['Is Resell'])) return (r.Detail || '').toLowerCase().includes(q);
      const u = userMap[r.Name] || { Name: 'Unknown User' };
      return (u.Name || '').toLowerCase().includes(q);
    });
  }, [data, deferredSearch, userMap]);

  const RENDER_CAP = 300;
  const visible = filtered.slice(0, RENDER_CAP);

  const submit = async (e) => {
    e.preventDefault();
    const isMoney = form['Contribution Type'] === '1';
    const isResell = isMoney && !!form['Is Resell'];
    const isUtrMode = isMoney && !isResell && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online');
    if (isResell) {
      if (!form.Detail.trim()) return alert("Resold item's name is required");
      if (!form.Amount) return alert('Amount is required');
    } else {
      if (!form.Name) return alert('Please select a contributor');
      if (isMoney && !form.Amount) return alert('Amount is required');
      if (!isMoney && !form.Detail.trim()) return alert('Detail is required (what was given / what work was done)');
    }
    setSaving(true);
    try {
      const payload = {
        Name: isResell ? '' : form.Name,
        'Payment Mode': isMoney ? form['Payment Mode'] : '',
        UTR: isUtrMode ? form.UTR : '',
        Date: form.Date,
        'Contribution Type': form['Contribution Type'],
        Amount: (isMoney || isResell) ? form.Amount : '',
        Detail: (isMoney && !isResell) ? '' : form.Detail,
        'Certificate Or Receipt': form['Contribution Type'] === '3' ? form['Certificate Or Receipt'] : '',
        'Is Resell': isResell ? 'TRUE' : 'FALSE',
      };
      let savedRowIndex;
      let genYear;
      const isNewEntry = !editing;
      if (editing) {
        genYear = editing.Year;
        savedRowIndex = editing.__rowIndex;
        // Neither `Sl. No.` (the receipt number) nor `Created By` is sent: the server owns
        // both and REJECTS them, which is what broke every edit here. An unsent column keeps
        // its stored value, because updateRecord builds `SET` from the keys it receives.
        await api.updateRecord('COLLECTIONS', editing.__rowIndex, { Year: editing.Year, ...payload });
      } else {
        genYear = year === 'All' ? new Date().getFullYear() : year;
        const res = await api.saveRecord('COLLECTIONS', { Year: genYear, ...payload });
        savedRowIndex = res.rowIndex;
      }
      invalidate('home:');

      const docType = autoGenerateDocType(payload);
      const genPayload = { Year: genYear, ...payload };
      const warnings = [];

      // FEAT-003: the document is now FILLED SERVER-SIDE (on Render). The browser
      // no longer builds the .docx or the QR — it enqueues REFERENCES ONLY
      // (docType, rowIndex, year). The server derives the recordId + payload from
      // the stored row (audit P0-03), resolves the template, dispatches the fill +
      // QR + PDF to Render, and on the callback writes the index and sends WhatsApp
      // then email in that order.
      setSavingStep('Adding to the queue...');
      try {
        await api.enqueueCollectionJob({
          docType: docType || '',
          year: genYear,
          rowIndex: savedRowIndex,
          isNewEntry,
        });
        api.processCollectionQueue().catch(() => {  });
        warnings.push('The document and WhatsApp message have been queued in the background — they will complete shortly.');
      } catch (err) {
        reportClientError('Home', 'enqueueCollectionJob failed', err,
          { docType, genYear, rowIndex: savedRowIndex });
        // The entry was saved; only the background queue failed. There is no
        // in-browser fallback any more (the fill is server-side) — surface it so
        // the operator can retry from the Queue Monitor.
        warnings.push('The entry was saved, but queuing the document/message failed: ' + err.message
          + ' A Superadmin can retry it from the Queue Monitor.');
      }

      setPostSaveWarning(warnings.join(' | '));
      setQueueBump(n => n + 1);
      closeModal();
      refresh();
    } catch (err) {
      alert(err.message);
    } finally {
      setSaving(false);
      setSavingStep('');
    }
  };

  // FEAT-003: the browser no longer fills the .docx or builds the QR for the auto
  // path — that moved server-side (Render). The old fillDocxForQueue (which imported
  // docxFill.js + qrCode.js and called getDocxTemplateForDoc / getReceiptData) is
  // gone, so this bundle no longer pulls docxtemplater/qrcode for the auto path.

  const closeModal = () => {
    setShowAdd(false);
    setEditing(null);
    setForm({
      Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
      Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
      Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
    });
  };

  const openEdit = (r) => {
    setEditing(r);
    setForm({
      Name: r.Name, Amount: r.Amount, 'Payment Mode': r['Payment Mode'] || 'Cash', UTR: r.UTR || '',
      Date: r.Date || new Date().toISOString().slice(0, 10),
      'Contribution Type': (r['Contribution Type'] ?? '').toString() || '1', Detail: r.Detail || '', 'Certificate Or Receipt': r['Certificate Or Receipt'] || 'Receipt',
      'Is Resell': r['Is Resell'] === 'TRUE' || r['Is Resell'] === true,
    });
    setShowAdd(true);
  };

  const remove = async (r) => {
    if (!confirm('Delete this collection entry?')) return;
    try {
      await api.deleteRecord('COLLECTIONS', r.__rowIndex);
      invalidate('home:');
      refresh();
    } catch (err) {
      alert(err.message);
    }
  };

  if (loading) return <div className="inline-spinner">Loading budget...</div>;
  if (error) return <div className="error-banner">{error}</div>;
  if (!data) return <div className="inline-spinner">Loading budget...</div>;

  return (
    <>
      <div className="glass-card budget-card">
        <h2 style={{ marginBottom: 15 }}>{year === 'All' ? 'Lifetime' : year} Budget Overview</h2>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
          <span>(+) Past Loan Returned</span><strong>{fmt(data.pastRet)}</strong>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 15 }}>
          <span>(+) Collection</span><strong style={{ color: '#34D399' }}>+{fmt(data.totCol)}</strong>
        </div>
        <div style={{ borderTop: '1px dashed #4B5563', paddingTop: 15, display: 'flex', justifyContent: 'space-between' }}>
          <strong>TOTAL BUDGET</strong><strong style={{ color: 'var(--primary-saffron)', fontSize: '1.5rem' }}>{fmt(data.totBudget)}</strong>
        </div>
      </div>

      <div className="grid-2" style={{ marginBottom: 20 }}>
        <div className="stat-box" style={{ borderColor: 'var(--danger)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Total Expense</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--danger)' }}>{fmt(data.totExp)}</div>
        </div>
        <div className="stat-box" style={{ borderColor: 'var(--success)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Net Surplus</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--success)' }}>{fmt(data.surplus)}</div>
        </div>
      </div>

      {postSaveWarning && (
        <div style={{ background: '#FEF3C7', color: '#92400E', borderRadius: 8, padding: '10px 12px', fontSize: '0.85rem', marginBottom: 12, display: 'flex', justifyContent: 'space-between', gap: 8 }}>
          <span>⚠️ The entry was saved, but: {postSaveWarning}</span>
          <span style={{ cursor: 'pointer', fontWeight: 700 }} onClick={() => setPostSaveWarning('')}>×</span>
        </div>
      )}

      {}
      <QueueStatus refreshKey={queueBump} />

      <h3 style={{ marginBottom: 15 }}>Collections (Contribution)</h3>
      <input placeholder="Search Contribution Data..." style={{ marginBottom: 15 }} value={search} onChange={e => setSearch(e.target.value)} />

      {
}
      {data.hasMore && (
        <div style={{ background: '#EFF6FF', color: '#1E40AF', borderRadius: 8, padding: '8px 12px', fontSize: '0.85rem', marginBottom: 12 }}>
          Showing the {data.shownRows} most recent of {data.totalRows} contributions.
          The totals above cover all of them. Select a specific year to see its complete list.
        </div>
      )}
      <div className="glass-card">
        {filtered.length === 0 && <div style={{ textAlign: 'center', padding: 20 }}>No records found.</div>}
        {visible.map((r) => {
          const isResellRow = r['Is Resell'] === 'TRUE' || r['Is Resell'] === true;
          const u = isResellRow ? null : (userMap[r.Name] || { Name: 'Unknown User', Village: '-' });
          return (
            <div className="data-row" key={r.__rowIndex}>
              <div>
                {isResellRow ? (
                  <strong style={{ display: 'block' }}>
                    ♻️ Resell: {r.Detail || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}
                  </strong>
                ) : (
                  <>
                    <strong style={{ display: 'block' }}>{u.Name} | {u.Designation || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}</strong>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{u["Father's Name"] || '-'} | {u.Village || '-'}</span>
                  </>
                )}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                {((r['Contribution Type'] ?? '').toString() || '1') === '1' ? (
                  <strong style={{ color: 'var(--success)' }}>+{fmt(r.Amount)}</strong>
                ) : (
                  <span className="badge" style={{ background: '#DBEAFE', color: '#1E40AF' }}>
                    {(r['Contribution Type'] ?? '').toString() === '2' ? 'Material' : 'Service'}{r['Certificate Or Receipt'] === 'Certificate' ? ' — Certificate' : ''}
                  </span>
                )}
                {!isResellRow && r.Detail && <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', maxWidth: 180, textAlign: 'right' }}>{r.Detail}</span>}
                {r['Payment Mode'] && <span className="badge" style={{ background: '#f3f4f6', color: '#374151' }}>{r['Payment Mode']}{paymentModeHindiOf(r['Payment Mode']) ? ` (${paymentModeHindiOf(r['Payment Mode'])})` : ''}</span>}
                {r.UTR && <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>UTR: {r.UTR}</span>}
                <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  <RowActions role={role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
                </div>
              </div>
            </div>
          );
        })}
        {filtered.length > RENDER_CAP && (
          <div style={{ textAlign: 'center', padding: 14, color: 'var(--text-muted)', fontSize: '0.85rem' }}>
            Showing {RENDER_CAP} of {filtered.length} matching rows — refine the search to narrow the list.
          </div>
        )}
      </div>

      {editable && canAddView(role, 'home') && (
        <button className="fab" onClick={() => setShowAdd(true)}><span className="material-icons-round">add</span></button>
      )}

      <Modal open={showAdd} onClose={closeModal}>
        <h3 style={{ marginBottom: 15 }}>{editing ? 'Edit Collection' : 'Add Collection'}</h3>
        <form onSubmit={submit}>
          <div className="form-group">
            <label>Contribution Type</label>
            <select
              value={form['Contribution Type']}
              onChange={e => setForm({ ...form, 'Contribution Type': e.target.value, 'Is Resell': e.target.value === '1' ? form['Is Resell'] : false })}
            >
              <option value="1">Cash (Money)</option>
              <option value="2">Material (Item)</option>
              <option value="3">Service (Work)</option>
            </select>
          </div>

          {form['Contribution Type'] === '1' && (
            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input
                type="checkbox"
                id="isResell"
                checked={!!form['Is Resell']}
                onChange={e => setForm({ ...form, 'Is Resell': e.target.checked, Name: '' })}
                style={{ width: 'auto' }}
              />
              <label htmlFor="isResell" style={{ margin: 0 }}>This is an entry for a resold item (no contributor)</label>
            </div>
          )}

          {form['Contribution Type'] === '1' && form['Is Resell'] ? (
            <div className="form-group">
              <label>Resold Item Name</label>
              <input value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} placeholder="e.g. Old utensils, clothes, etc." />
            </div>
          ) : (
            <div className="form-group">
              <label>Contributor</label>
              <SearchableSelect
                options={userOptions}
                value={form.Name}
                onChange={id => setForm({ ...form, Name: id })}
                placeholder="Search name or village..."
                onAddNew={() => setShowQuickAdd(true)}
              />
            </div>
          )}

          {form.Name && !form['Is Resell'] && (
            <div className="form-group" style={{ background: '#f9fafb', borderRadius: 8, padding: '10px 12px' }}>
              <label style={{ marginBottom: 6 }}>Last 5 Years Contribution</label>
              {historyLoading && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Loading...</div>}
              {!historyLoading && (!history || history.length === 0) && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>No prior contributions</div>}
              {!historyLoading && history && history.map(h => {
                const tags = [];
                if (h.HasSamaan) tags.push('Material');
                if (h.HasKaam) tags.push('Service');
                return (
                  <div key={h.Year} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', padding: '3px 0' }}>
                    <span>{h.Year}</span>
                    <span>
                      {h.Amount > 0 && <strong style={{ color: 'var(--success)' }}>{fmt(h.Amount)}</strong>}
                      {tags.length > 0 && <span style={{ color: 'var(--text-muted)' }}>{h.Amount > 0 ? ' + ' : ''}{tags.join(', ')}</span>}
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {(form['Contribution Type'] === '1') ? (
            <div className="form-group">
              <label>Amount</label>
              <input type="number" value={form.Amount} onChange={e => setForm({ ...form, Amount: e.target.value })} />
            </div>
          ) : (
            <div className="form-group">
              <label>{form['Contribution Type'] === '2' ? 'What was given (Item Detail)' : 'What work was done (Work Detail)'}</label>
              <textarea rows={2} value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} style={{ width: '100%', padding: 8, borderRadius: 8, border: '1px solid #ddd' }} />
            </div>
          )}

          {form['Contribution Type'] === '3' && (
            <div className="form-group">
              <label>Document Type</label>
              <select value={form['Certificate Or Receipt']} onChange={e => setForm({ ...form, 'Certificate Or Receipt': e.target.value })}>
                <option value="Receipt">Receipt</option>
                <option value="Certificate">Certificate</option>
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (
            <div className="form-group">
              <label>Payment Mode</label>
              <select value={form['Payment Mode']} onChange={e => setForm({ ...form, 'Payment Mode': e.target.value })}>
                {paymentModeOptions.map(p => (
                  <option key={p['English Value']} value={p['English Value']}>
                    {p['English Value']}{p['Hindi Label'] ? ` (${p['Hindi Label']})` : ''}
                  </option>
                ))}
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online') && (
            <div className="form-group">
              <label>UTR / Transaction ID</label>
              <input value={form.UTR} onChange={e => setForm({ ...form, UTR: e.target.value })} placeholder="UPI/Bank UTR number" />
            </div>
          )}

          <div className="form-group">
            <label>Date</label>
            <input type="date" value={form.Date} onChange={e => setForm({ ...form, Date: e.target.value })} />
          </div>
          <button className="btn-submit" disabled={saving}>{saving ? (savingStep || 'Saving...') : 'Save'}</button>
        </form>
      </Modal>

      <QuickAddUser
        open={showQuickAdd}
        onClose={() => setShowQuickAdd(false)}
        onCreated={(id) => { onUserCreated(); setForm(f => ({ ...f, Name: id })); }}
      />

    </>
  );
}
