import { useState, useMemo, useEffect, lazy, Suspense } from 'react';
import { api, fmt } from '../api.js';
import { useViewData } from '../useViewData.js';
import { invalidate } from '../cache.js';
import Modal from '../components/Modal.jsx';
import SearchableSelect from '../components/SearchableSelect.jsx';
import QuickAddUser from '../components/QuickAddUser.jsx';
import RowActions from '../components/RowActions.jsx';
// Pulls in jsPDF + html2canvas — lazy so Home (a core, always-loaded tab)
// doesn't ship those to every user on first load, only when Download is clicked.
const ReceiptModal = lazy(() => import('../components/ReceiptModal.jsx'));
import { canAddView } from '../permissions.js';
import { useDropdownList } from '../useDropdownList.js';

// Decides which doc-type (if any) should auto-generate silently right after
// Save/Edit. Paisa (Cash) -> receipt, Samaan (Material) -> samaan, Kaam (Service)+Receipt -> receipt,
// Kaam (Service)+Certificate -> certificate. Resell has no document concept at all, so
// it returns null (no auto-generate, and its WhatsApp message queues without
// waiting on any file).
function autoGenerateDocType(payload) {
  if (payload['Is Resell'] === 'TRUE') return null;
  const type = payload['Contribution Type'];
  if (type === '1') return 'receipt';
  if (type === '2') return 'samaan';
  if (type === '3') return payload['Certificate Or Receipt'] === 'Certificate' ? 'certificate' : 'receipt';
  return null;
}

const AUTO_GENERATE_FETCH = {
  receipt: (api, rowIndex, year) => api.getReceiptData(rowIndex, year),
  certificate: (api, rowIndex, year) => api.getCertificateData(rowIndex, year),
  samaan: (api, rowIndex, year) => api.getSamaanData(rowIndex, year),
};
const AUTO_GENERATE_DOC_NO_KEY = { receipt: 'RECEIPT_NO', certificate: 'CERT_NO', samaan: 'SAMAAN_NO' };

export default function Home({ year, users, onUserCreated, role, editable }) {
  const [receiptRow, setReceiptRow] = useState(null);
  const { data, loading, error, refresh } = useViewData(`home:${year}`, () => api.getHome(year), [year]);
  const { options: paymentModeOptions, hindiOf: paymentModeHindiOf } = useDropdownList('Payment Mode');
  const [search, setSearch] = useState('');
  const [showAdd, setShowAdd] = useState(false);
  const [showQuickAdd, setShowQuickAdd] = useState(false);
  const [form, setForm] = useState({
    Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
    Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
    Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
  });
  const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState(null); // holds the row being edited, or null when adding
  const [history, setHistory] = useState(null);
  const [historyLoading, setHistoryLoading] = useState(false);

  const userMap = useMemo(() => {
    const m = {};
    (users || []).forEach(u => { m[u.ID] = u; });
    return m;
  }, [users]);

  const userOptions = useMemo(() => (users || []).map(u => ({ value: u.ID, label: u.Name, sub: u.Village })), [users]);

  useEffect(() => {
    if (!form.Name) { setHistory(null); return; }
    setHistoryLoading(true);
    api.getUserHistory(form.Name).then(setHistory).catch(() => setHistory(null)).finally(() => setHistoryLoading(false));
  }, [form.Name]);

  const filtered = (data?.collections || []).filter(r => {
    const u = userMap[r.Name] || { Name: 'Unknown User' };
    return u.Name.toLowerCase().includes(search.toLowerCase());
  });

  const submit = async (e) => {
    e.preventDefault();
    const isMoney = form['Contribution Type'] === '1';
    const isResell = isMoney && !!form['Is Resell'];
    const isUtrMode = isMoney && !isResell && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online');
    if (isResell) {
      if (!form.Detail.trim()) return alert("Resold item's name is required");
      if (!form.Amount) return alert('Amount is required');
    } else {
      if (!form.Name) return alert('Please select a contributor');
      if (isMoney && !form.Amount) return alert('Amount is required');
      if (!isMoney && !form.Detail.trim()) return alert('Detail is required (what was given / what work was done)');
    }
    setSaving(true);
    try {
      const payload = {
        Name: isResell ? '' : form.Name,
        'Payment Mode': isMoney ? form['Payment Mode'] : '',
        UTR: isUtrMode ? form.UTR : '',
        Date: form.Date,
        'Contribution Type': form['Contribution Type'],
        Amount: (isMoney || isResell) ? form.Amount : '',
        Detail: (isMoney && !isResell) ? '' : form.Detail,
        'Certificate Or Receipt': form['Contribution Type'] === '3' ? form['Certificate Or Receipt'] : '',
        'Is Resell': isResell ? 'TRUE' : 'FALSE',
      };
      let savedRowIndex;
      let genYear;
      const isNewEntry = !editing;
      if (editing) {
        genYear = editing.Year;
        savedRowIndex = editing.__rowIndex;
        await api.updateRecord('COLLECTIONS', editing.__rowIndex, { Year: editing.Year, 'Sl. No.': editing['Sl. No.'], ...payload, 'Created By': editing['Created By'] });
      } else {
        genYear = year === 'All' ? new Date().getFullYear() : year;
        const res = await api.saveRecord('COLLECTIONS', { Year: genYear, ...payload });
        savedRowIndex = res.rowIndex;
      }
      invalidate('home:');
      closeModal();
      refresh();

      // Silent background flow — no modal, no extra click, never blocks the
      // save or shows an error to the user. Only on a brand-new entry (not an
      // edit) do we go on to queue the WhatsApp messages, and only AFTER this
      // recipient's own PDF has finished generating (or failed) — so the
      // right message goes out with the right person's own file attached,
      // never a stale/static link and never someone else's file.
      const docType = autoGenerateDocType(payload);
      const genPayload = { Year: genYear, ...payload };
      if (docType && savedRowIndex) {
        autoGeneratePdf(docType, savedRowIndex, genYear).then(fileLink => {
          if (isNewEntry) {
            api.queueCollectionMessages(genPayload, savedRowIndex, fileLink || '')
              .catch(err => console.warn('Queue WhatsApp messages failed:', err));
          }
        });
      } else if (isNewEntry) {
        // No document concept for this entry (e.g. Resell) — nothing to wait
        // on, queue the WhatsApp messages right away.
        api.queueCollectionMessages(genPayload, savedRowIndex, '')
          .catch(err => console.warn('Queue WhatsApp messages failed:', err));
      }
    } catch (err) {
      alert(err.message);
    } finally {
      setSaving(false);
    }
  };

  // Returns the generated PDF's public link on success, or null (template
  // missing, fetch/fill/convert failed, etc.) — never throws, so a failure
  // here never interrupts the user's flow or the save itself. The caller
  // queues the WhatsApp message without a file link when this returns null.
  const autoGeneratePdf = async (docType, rowIndex, genYear) => {
    try {
      const docxRow = await api.getDocxTemplateForDoc(docType, genYear).catch(() => null);
      if (!docxRow || (!docxRow.base64 && !docxRow.downloadUrl)) return null; // no template yet — silent skip

      const dataFetcher = AUTO_GENERATE_FETCH[docType];
      if (!dataFetcher) return null;
      const data = await dataFetcher(api, rowIndex, genYear);
      const docNoKey = AUTO_GENERATE_DOC_NO_KEY[docType];
      const recordId = `${docType}-${genYear}-${rowIndex}`;

      // docxFill (docxtemplater + pizzip) is a fairly heavy dependency — load it
      // only when we actually need to auto-generate, same reasoning as why
      // ReceiptModal itself is lazy-loaded.
      const { fillDocxTemplateFromRow } = await import('../docxFill.js');
      const { generateQrDataUrl, publicRecordUrl } = await import('../qrCode.js');
      const qrCode = await generateQrDataUrl(publicRecordUrl(recordId)).catch(() => '');
      const placeholders = { ...data.placeholders, GENERATED_AT: new Date().toLocaleString('en-IN'), QR_CODE: qrCode };

      const filledBase64 = await fillDocxTemplateFromRow(docxRow, placeholders);
      const fileName = `${docType}-${placeholders[docNoKey]}.docx`;
      const res = await api.convertDocxToPdf(docType, genYear, recordId, filledBase64, fileName, true);
      return (res && res.publicLink) ? res.publicLink : null;
    } catch (err) {
      // Silent by design — auto-generate should never interrupt the user's flow.
      console.warn('Auto-generate PDF failed:', err);
      return null;
    }
  };

  const closeModal = () => {
    setShowAdd(false);
    setEditing(null);
    setForm({
      Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
      Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
      Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
    });
  };

  const openEdit = (r) => {
    setEditing(r);
    setForm({
      Name: r.Name, Amount: r.Amount, 'Payment Mode': r['Payment Mode'] || 'Cash', UTR: r.UTR || '',
      Date: r.Date || new Date().toISOString().slice(0, 10),
      'Contribution Type': (r['Contribution Type'] ?? '').toString() || '1', Detail: r.Detail || '', 'Certificate Or Receipt': r['Certificate Or Receipt'] || 'Receipt',
      'Is Resell': r['Is Resell'] === 'TRUE' || r['Is Resell'] === true,
    });
    setShowAdd(true);
  };

  const remove = async (r) => {
    if (!confirm('Delete this collection entry?')) return;
    try {
      await api.deleteRecord('COLLECTIONS', r.__rowIndex);
      invalidate('home:');
      refresh();
    } catch (err) {
      alert(err.message);
    }
  };

  if (loading) return <div className="inline-spinner">Loading budget...</div>;
  if (error) return <div className="error-banner">{error}</div>;

  return (
    <>
      <div className="glass-card budget-card">
        <h2 style={{ marginBottom: 15 }}>{year === 'All' ? 'Lifetime' : year} Budget Overview</h2>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
          <span>(+) Past Loan Returned</span><strong>{fmt(data.pastRet)}</strong>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 15 }}>
          <span>(+) Collection</span><strong style={{ color: '#34D399' }}>+{fmt(data.totCol)}</strong>
        </div>
        <div style={{ borderTop: '1px dashed #4B5563', paddingTop: 15, display: 'flex', justifyContent: 'space-between' }}>
          <strong>TOTAL BUDGET</strong><strong style={{ color: 'var(--primary-saffron)', fontSize: '1.5rem' }}>{fmt(data.totBudget)}</strong>
        </div>
      </div>

      <div className="grid-2" style={{ marginBottom: 20 }}>
        <div className="stat-box" style={{ borderColor: 'var(--danger)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Total Expense</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--danger)' }}>{fmt(data.totExp)}</div>
        </div>
        <div className="stat-box" style={{ borderColor: 'var(--success)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Net Surplus</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--success)' }}>{fmt(data.surplus)}</div>
        </div>
      </div>

      <h3 style={{ marginBottom: 15 }}>Collections (Contribution)</h3>
      <input placeholder="Search Contribution Data..." style={{ marginBottom: 15 }} value={search} onChange={e => setSearch(e.target.value)} />
      <div className="glass-card">
        {filtered.length === 0 && <div style={{ textAlign: 'center', padding: 20 }}>No records found.</div>}
        {filtered.map((r, i) => {
          const isResellRow = r['Is Resell'] === 'TRUE' || r['Is Resell'] === true;
          const u = isResellRow ? null : (userMap[r.Name] || { Name: 'Unknown User', Village: '-' });
          return (
            <div className="data-row" key={i}>
              <div>
                {isResellRow ? (
                  <strong style={{ display: 'block' }}>
                    ♻️ Resell: {r.Detail || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}
                  </strong>
                ) : (
                  <>
                    <strong style={{ display: 'block' }}>{u.Name} | {u.Designation || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}</strong>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{u["Father's Name"] || '-'} | {u.Village || '-'}</span>
                  </>
                )}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                {((r['Contribution Type'] ?? '').toString() || '1') === '1' ? (
                  <strong style={{ color: 'var(--success)' }}>+{fmt(r.Amount)}</strong>
                ) : (
                  <span className="badge" style={{ background: '#DBEAFE', color: '#1E40AF' }}>
                    {(r['Contribution Type'] ?? '').toString() === '2' ? 'Material' : 'Service'}{r['Certificate Or Receipt'] === 'Certificate' ? ' — Certificate' : ''}
                  </span>
                )}
                {!isResellRow && r.Detail && <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', maxWidth: 180, textAlign: 'right' }}>{r.Detail}</span>}
                {r['Payment Mode'] && <span className="badge" style={{ background: '#f3f4f6', color: '#374151' }}>{r['Payment Mode']}{paymentModeHindiOf(r['Payment Mode']) ? ` (${paymentModeHindiOf(r['Payment Mode'])})` : ''}</span>}
                {r.UTR && <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>UTR: {r.UTR}</span>}
                <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  {!isResellRow && (
                    <span
                      className="material-icons-round"
                      style={{ cursor: 'pointer', fontSize: '1.1rem', color: 'var(--primary-saffron)' }}
                      title={(r['Contribution Type'] ?? '').toString() === '2' ? 'Download Material Receipt' : r['Certificate Or Receipt'] === 'Certificate' ? 'Download Certificate' : 'Download Receipt'}
                      onClick={() => setReceiptRow(r)}
                    >
                      download
                    </span>
                  )}
                  <RowActions role={role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {editable && canAddView(role, 'home') && (
        <button className="fab" onClick={() => setShowAdd(true)}><span className="material-icons-round">add</span></button>
      )}

      <Modal open={showAdd} onClose={closeModal}>
        <h3 style={{ marginBottom: 15 }}>{editing ? 'Edit Collection' : 'Add Collection'}</h3>
        <form onSubmit={submit}>
          <div className="form-group">
            <label>Contribution Type</label>
            <select
              value={form['Contribution Type']}
              onChange={e => setForm({ ...form, 'Contribution Type': e.target.value, 'Is Resell': e.target.value === '1' ? form['Is Resell'] : false })}
            >
              <option value="1">Cash (Money)</option>
              <option value="2">Material (Item)</option>
              <option value="3">Service (Work)</option>
            </select>
          </div>

          {form['Contribution Type'] === '1' && (
            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input
                type="checkbox"
                id="isResell"
                checked={!!form['Is Resell']}
                onChange={e => setForm({ ...form, 'Is Resell': e.target.checked, Name: '' })}
                style={{ width: 'auto' }}
              />
              <label htmlFor="isResell" style={{ margin: 0 }}>This is an entry for a resold item (no contributor)</label>
            </div>
          )}

          {form['Contribution Type'] === '1' && form['Is Resell'] ? (
            <div className="form-group">
              <label>Resold Item Name</label>
              <input value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} placeholder="e.g. Old utensils, clothes, etc." />
            </div>
          ) : (
            <div className="form-group">
              <label>Contributor</label>
              <SearchableSelect
                options={userOptions}
                value={form.Name}
                onChange={id => setForm({ ...form, Name: id })}
                placeholder="Search name or village..."
                onAddNew={() => setShowQuickAdd(true)}
              />
            </div>
          )}

          {form.Name && !form['Is Resell'] && (
            <div className="form-group" style={{ background: '#f9fafb', borderRadius: 8, padding: '10px 12px' }}>
              <label style={{ marginBottom: 6 }}>Last 5 Years Contribution</label>
              {historyLoading && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Loading...</div>}
              {!historyLoading && (!history || history.length === 0) && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>No prior contributions</div>}
              {!historyLoading && history && history.map(h => {
                const tags = [];
                if (h.HasSamaan) tags.push('Material');
                if (h.HasKaam) tags.push('Service');
                return (
                  <div key={h.Year} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', padding: '3px 0' }}>
                    <span>{h.Year}</span>
                    <span>
                      {h.Amount > 0 && <strong style={{ color: 'var(--success)' }}>{fmt(h.Amount)}</strong>}
                      {tags.length > 0 && <span style={{ color: 'var(--text-muted)' }}>{h.Amount > 0 ? ' + ' : ''}{tags.join(', ')}</span>}
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {(form['Contribution Type'] === '1') ? (
            <div className="form-group">
              <label>Amount</label>
              <input type="number" value={form.Amount} onChange={e => setForm({ ...form, Amount: e.target.value })} />
            </div>
          ) : (
            <div className="form-group">
              <label>{form['Contribution Type'] === '2' ? 'What was given (Item Detail)' : 'What work was done (Work Detail)'}</label>
              <textarea rows={2} value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} style={{ width: '100%', padding: 8, borderRadius: 8, border: '1px solid #ddd' }} />
            </div>
          )}

          {form['Contribution Type'] === '3' && (
            <div className="form-group">
              <label>Document Type</label>
              <select value={form['Certificate Or Receipt']} onChange={e => setForm({ ...form, 'Certificate Or Receipt': e.target.value })}>
                <option value="Receipt">Receipt</option>
                <option value="Certificate">Certificate</option>
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (
            <div className="form-group">
              <label>Payment Mode</label>
              <select value={form['Payment Mode']} onChange={e => setForm({ ...form, 'Payment Mode': e.target.value })}>
                {paymentModeOptions.map(p => (
                  <option key={p['English Value']} value={p['English Value']}>
                    {p['English Value']}{p['Hindi Label'] ? ` (${p['Hindi Label']})` : ''}
                  </option>
                ))}
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online') && (
            <div className="form-group">
              <label>UTR / Transaction ID</label>
              <input value={form.UTR} onChange={e => setForm({ ...form, UTR: e.target.value })} placeholder="UPI/Bank UTR number" />
            </div>
          )}

          <div className="form-group">
            <label>Date</label>
            <input type="date" value={form.Date} onChange={e => setForm({ ...form, Date: e.target.value })} />
          </div>
          <button className="btn-submit" disabled={saving}>{saving ? 'Saving...' : 'Save'}</button>
        </form>
      </Modal>

      <QuickAddUser
        open={showQuickAdd}
        onClose={() => setShowQuickAdd(false)}
        onCreated={(id) => { onUserCreated(); setForm(f => ({ ...f, Name: id })); }}
      />

      <Suspense fallback={null}>
        <ReceiptModal
          row={receiptRow}
          year={receiptRow ? receiptRow.Year : year}
          open={!!receiptRow}
          onClose={() => setReceiptRow(null)}
          docType={
            receiptRow && receiptRow['Contribution Type'] === '2' ? 'samaan'
            : receiptRow && receiptRow['Certificate Or Receipt'] === 'Certificate' ? 'certificate'
            : 'receipt'
          }
        />
      </Suspense>
    </>
  );
}
