import { useState, useMemo, useEffect, lazy, Suspense } from 'react';
import { api, fmt, reportClientError } from '../api.js';
import { safeImport } from '../chunkGuard.js';
import { useViewData } from '../useViewData.js';
import { invalidate } from '../cache.js';
import Modal from '../components/Modal.jsx';
import SearchableSelect from '../components/SearchableSelect.jsx';
import QuickAddUser from '../components/QuickAddUser.jsx';
import RowActions from '../components/RowActions.jsx';
import QueueStatus from '../components/QueueStatus.jsx';
// Pulls in jsPDF + html2canvas — lazy so Home (a core, always-loaded tab)
// doesn't ship those to every user on first load, only when Download is clicked.
const ReceiptModal = lazy(() => import('../components/ReceiptModal.jsx'));
import { canAddView } from '../permissions.js';
import { useDropdownList } from '../useDropdownList.js';

// Decides which doc-type (if any) should auto-generate silently right after
// Save/Edit. Paisa (Cash) -> receipt, Samaan (Material) -> samaan, Kaam (Service)+Receipt -> receipt,
// Kaam (Service)+Certificate -> certificate. Resell has no document concept at all, so
// it returns null (no auto-generate, and its WhatsApp message queues without
// waiting on any file).
function autoGenerateDocType(payload) {
  if (payload['Is Resell'] === 'TRUE') return null;
  const type = payload['Contribution Type'];
  if (type === '1') return 'receipt';
  if (type === '2') return 'samaan';
  if (type === '3') return payload['Certificate Or Receipt'] === 'Certificate' ? 'certificate' : 'receipt';
  return null;
}

const AUTO_GENERATE_FETCH = {
  receipt: (api, rowIndex, year) => api.getReceiptData(rowIndex, year),
  certificate: (api, rowIndex, year) => api.getCertificateData(rowIndex, year),
  samaan: (api, rowIndex, year) => api.getSamaanData(rowIndex, year),
};
const AUTO_GENERATE_DOC_NO_KEY = { receipt: 'RECEIPT_NO', certificate: 'CERT_NO', samaan: 'SAMAAN_NO' };

export default function Home({ year, users, onUserCreated, role, editable }) {
  const [receiptRow, setReceiptRow] = useState(null);
  const { data, loading, error, refresh } = useViewData(`home:${year}`, () => api.getHome(year), [year]);
  const { options: paymentModeOptions, hindiOf: paymentModeHindiOf } = useDropdownList('Payment Mode');
  const [search, setSearch] = useState('');
  const [showAdd, setShowAdd] = useState(false);
  const [showQuickAdd, setShowQuickAdd] = useState(false);
  const [form, setForm] = useState({
    Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
    Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
    Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
  });
  const [saving, setSaving] = useState(false);
  const [savingStep, setSavingStep] = useState('');
  const [postSaveWarning, setPostSaveWarning] = useState('');
  const [queueBump, setQueueBump] = useState(0); // bump after a save so QueueStatus re-polls
  const [editing, setEditing] = useState(null); // holds the row being edited, or null when adding
  const [history, setHistory] = useState(null);
  const [historyLoading, setHistoryLoading] = useState(false);

  const userMap = useMemo(() => {
    const m = {};
    (users || []).forEach(u => { m[u.ID] = u; });
    return m;
  }, [users]);

  const userOptions = useMemo(() => (users || []).map(u => ({ value: u.ID, label: u.Name, sub: u.Village })), [users]);

  useEffect(() => {
    if (!form.Name) { setHistory(null); return; }
    setHistoryLoading(true);
    api.getUserHistory(form.Name).then(setHistory).catch(() => setHistory(null)).finally(() => setHistoryLoading(false));
  }, [form.Name]);

  const filtered = (data?.collections || []).filter(r => {
    const q = search.toLowerCase();
    // A resell row has no contributor — it's searchable by its item name (Detail),
    // not by "Unknown User" (which is what matching on userMap used to fall back to).
    const isResellRow = r['Is Resell'] === true || r['Is Resell'] === 'TRUE'
      || (typeof r['Is Resell'] === 'string' && r['Is Resell'].trim().toLowerCase() === 'true');
    if (isResellRow) return (r.Detail || '').toLowerCase().includes(q);
    const u = userMap[r.Name] || { Name: 'Unknown User' };
    return (u.Name || '').toLowerCase().includes(q);
  });

  const submit = async (e) => {
    e.preventDefault();
    const isMoney = form['Contribution Type'] === '1';
    const isResell = isMoney && !!form['Is Resell'];
    const isUtrMode = isMoney && !isResell && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online');
    if (isResell) {
      if (!form.Detail.trim()) return alert("Resold item's name is required");
      if (!form.Amount) return alert('Amount is required');
    } else {
      if (!form.Name) return alert('Please select a contributor');
      if (isMoney && !form.Amount) return alert('Amount is required');
      if (!isMoney && !form.Detail.trim()) return alert('Detail is required (what was given / what work was done)');
    }
    setSaving(true);
    try {
      const payload = {
        Name: isResell ? '' : form.Name,
        'Payment Mode': isMoney ? form['Payment Mode'] : '',
        UTR: isUtrMode ? form.UTR : '',
        Date: form.Date,
        'Contribution Type': form['Contribution Type'],
        Amount: (isMoney || isResell) ? form.Amount : '',
        Detail: (isMoney && !isResell) ? '' : form.Detail,
        'Certificate Or Receipt': form['Contribution Type'] === '3' ? form['Certificate Or Receipt'] : '',
        'Is Resell': isResell ? 'TRUE' : 'FALSE',
      };
      let savedRowIndex;
      let genYear;
      const isNewEntry = !editing;
      if (editing) {
        genYear = editing.Year;
        savedRowIndex = editing.__rowIndex;
        await api.updateRecord('COLLECTIONS', editing.__rowIndex, { Year: editing.Year, 'Sl. No.': editing['Sl. No.'], ...payload, 'Created By': editing['Created By'] });
      } else {
        genYear = year === 'All' ? new Date().getFullYear() : year;
        const res = await api.saveRecord('COLLECTIONS', { Year: genYear, ...payload });
        savedRowIndex = res.rowIndex;
      }
      invalidate('home:');

      // The record is saved. Everything after this point (PDF + WhatsApp) is a
      // follow-up, but it is now AWAITED instead of fire-and-forget.
      //
      // The old code did:
      //   autoGeneratePdf(...).then(fileLink => { api.queueCollectionMessages(...) })
      // un-awaited, and closed the modal + set saving=false immediately — so the
      // user was told the save was complete while a multi-second, multi-request
      // chain was still running in the background. Closing the tab, navigating
      // away, or a flaky network killed that chain: no PDF, no index row, AND
      // THE WHATSAPP MESSAGE WAS NEVER QUEUED AT ALL — silently, with nothing in
      // error_log because no catch ever fired. The .then() callback also had no
      // .catch, so a throw inside it became an unhandled rejection.
      // ---- NEW: enqueue a background job instead of awaiting PDF + WhatsApp ----
      //
      // The slow steps (docx->PDF conversion via Drive, then WhatsApp queueing)
      // now run server-side from a Cron Trigger. Here we only do the FAST part —
      // fill the .docx template in the browser (unchanged) — then hand the filled
      // bytes to the queue and return immediately. This is what makes Save feel
      // instant for every role. If enqueuing fails, we fall back to the old
      // inline path so a save is never left without its PDF/WhatsApp.
      const docType = autoGenerateDocType(payload);
      const genPayload = { Year: genYear, ...payload };
      const warnings = [];

      let filled = { filledBase64: '', fileName: '' };
      if (docType && savedRowIndex) {
        setSavingStep('Document taiyar kar rahe hain...');
        const fillResult = await fillDocxForQueue(docType, savedRowIndex, genYear);
        filled = { filledBase64: fillResult.filledBase64 || '', fileName: fillResult.fileName || '' };
        if (fillResult.warning) warnings.push(fillResult.warning);
      }

      setSavingStep('Queue mein daal rahe hain...');
      try {
        await api.enqueueCollectionJob({
          docType: docType || '',
          year: genYear,
          rowIndex: savedRowIndex,
          recordId: (docType && savedRowIndex) ? `${docType}-${genYear}-${savedRowIndex}` : '',
          isNewEntry,
          payload: genPayload,
          filledBase64: filled.filledBase64,
          fileName: filled.fileName,
        });
        warnings.push('PDF aur WhatsApp background mein queue ho gaye — thodi der mein complete honge.');
      } catch (err) {
        // FALLBACK: queue unreachable — do it inline the old way so nothing is lost.
        reportClientError('Home', 'enqueueCollectionJob failed — falling back to inline', err,
          { docType, genYear, rowIndex: savedRowIndex });
        let fileLink = '';
        if (docType && savedRowIndex && filled.filledBase64) {
          try {
            const res = await api.convertDocxToPdf(docType, genYear,
              `${docType}-${genYear}-${savedRowIndex}`, filled.filledBase64, filled.fileName, 'auto');
            fileLink = (res && res.publicLink) || '';
          } catch (e2) { warnings.push('PDF generate nahi hua: ' + e2.message); }
        }
        if (isNewEntry) {
          try {
            await api.queueCollectionMessages(genPayload, savedRowIndex, fileLink);
          } catch (e3) {
            warnings.push('WhatsApp message queue nahi hua: ' + e3.message);
          }
        }
      }

      setPostSaveWarning(warnings.join(' | '));
      setQueueBump(n => n + 1);
      closeModal();
      refresh();
    } catch (err) {
      alert(err.message);
    } finally {
      setSaving(false);
      setSavingStep('');
    }
  };

  // Returns { publicLink, warning } — never throws, so a PDF failure still can't
  // interrupt the save or block the WhatsApp message. Unlike before, the failure
  // is now REPORTED back to the caller (and to error_log) instead of collapsing
  // into a bare `null` that looked identical to "no template configured".
  // Fills the .docx template CLIENT-SIDE (docxtemplater + QR) and returns the
  // filled bytes as base64 for the background queue — it does NOT convert to PDF
  // or queue WhatsApp anymore (the Cron Trigger does that server-side). Returns
  // { filledBase64, fileName, warning } and never throws, so a fill problem can't
  // block the save — the record is already saved and the job still enqueues (for
  // the WhatsApp step), just without an attached document.
  const fillDocxForQueue = async (docType, rowIndex, genYear) => {
    const recordId = `${docType}-${genYear}-${rowIndex}`;
    try {
      let docxRow;
      try {
        docxRow = await api.getDocxTemplateForDoc(docType, genYear);
      } catch (err) {
        // A genuine failure (permissions / Drive error) — distinct from "no
        // template uploaded yet".
        reportClientError('Home', `autoPdf template load failed for ${docType} ${genYear}`, err,
          { docType, genYear, rowIndex });
        return { filledBase64: '', fileName: '', warning: `PDF template load nahi hua: ${err.message}` };
      }
      if (!docxRow || (!docxRow.base64 && !docxRow.downloadUrl)) {
        // Genuinely not configured — expected, not an error.
        return { filledBase64: '', fileName: '', warning: '' };
      }

      const dataFetcher = AUTO_GENERATE_FETCH[docType];
      if (!dataFetcher) return { filledBase64: '', fileName: '', warning: '' };
      const data = await dataFetcher(api, rowIndex, genYear);
      const docNoKey = AUTO_GENERATE_DOC_NO_KEY[docType];

      // docxFill (docxtemplater + pizzip) is heavy — lazy-load only when needed.
      const { fillDocxTemplateFromRow, getLastRenderReport } = await safeImport(() => import('../docxFill.js'), 'docxFill');
      const { generateQrDataUrl, publicRecordUrl } = await safeImport(() => import('../qrCode.js'), 'qrCode');

      let qrCode = '';
      try {
        qrCode = await generateQrDataUrl(publicRecordUrl(recordId));
      } catch (qrErr) {
        reportClientError('Home', `autoPdf QR generation failed for ${recordId}`, qrErr,
          { docType, genYear, rowIndex, recordId });
      }

      const placeholders = { ...data.placeholders, GENERATED_AT: new Date().toLocaleString('en-IN'), QR_CODE: qrCode };
      const filledBase64 = await fillDocxTemplateFromRow(docxRow, placeholders);

      const rep = getLastRenderReport();
      if (rep.missingTags.length) {
        reportClientError('Home', `autoPdf unresolved placeholders for ${recordId}`, null,
          { docType, genYear, recordId, missingTags: [...new Set(rep.missingTags)] });
      }

      const fileName = `${docType}-${placeholders[docNoKey]}.docx`;
      return { filledBase64, fileName, warning: qrCode ? '' : 'PDF ka QR blank hai.' };
    } catch (err) {
      reportClientError('Home', `autoPdf fill failed for ${recordId}`, err, { docType, genYear, rowIndex });
      return { filledBase64: '', fileName: '', warning: 'Document taiyar nahi hua: ' + err.message };
    }
  };

  const closeModal = () => {
    setShowAdd(false);
    setEditing(null);
    setForm({
      Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
      Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
      Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
    });
  };

  const openEdit = (r) => {
    setEditing(r);
    setForm({
      Name: r.Name, Amount: r.Amount, 'Payment Mode': r['Payment Mode'] || 'Cash', UTR: r.UTR || '',
      Date: r.Date || new Date().toISOString().slice(0, 10),
      'Contribution Type': (r['Contribution Type'] ?? '').toString() || '1', Detail: r.Detail || '', 'Certificate Or Receipt': r['Certificate Or Receipt'] || 'Receipt',
      'Is Resell': r['Is Resell'] === 'TRUE' || r['Is Resell'] === true,
    });
    setShowAdd(true);
  };

  const remove = async (r) => {
    if (!confirm('Delete this collection entry?')) return;
    try {
      await api.deleteRecord('COLLECTIONS', r.__rowIndex);
      invalidate('home:');
      refresh();
    } catch (err) {
      alert(err.message);
    }
  };

  if (loading) return <div className="inline-spinner">Loading budget...</div>;
  if (error) return <div className="error-banner">{error}</div>;

  return (
    <>
      <div className="glass-card budget-card">
        <h2 style={{ marginBottom: 15 }}>{year === 'All' ? 'Lifetime' : year} Budget Overview</h2>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
          <span>(+) Past Loan Returned</span><strong>{fmt(data.pastRet)}</strong>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 15 }}>
          <span>(+) Collection</span><strong style={{ color: '#34D399' }}>+{fmt(data.totCol)}</strong>
        </div>
        <div style={{ borderTop: '1px dashed #4B5563', paddingTop: 15, display: 'flex', justifyContent: 'space-between' }}>
          <strong>TOTAL BUDGET</strong><strong style={{ color: 'var(--primary-saffron)', fontSize: '1.5rem' }}>{fmt(data.totBudget)}</strong>
        </div>
      </div>

      <div className="grid-2" style={{ marginBottom: 20 }}>
        <div className="stat-box" style={{ borderColor: 'var(--danger)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Total Expense</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--danger)' }}>{fmt(data.totExp)}</div>
        </div>
        <div className="stat-box" style={{ borderColor: 'var(--success)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Net Surplus</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--success)' }}>{fmt(data.surplus)}</div>
        </div>
      </div>

      {postSaveWarning && (
        <div style={{ background: '#FEF3C7', color: '#92400E', borderRadius: 8, padding: '10px 12px', fontSize: '0.85rem', marginBottom: 12, display: 'flex', justifyContent: 'space-between', gap: 8 }}>
          <span>⚠️ Entry save ho gayi, lekin: {postSaveWarning}</span>
          <span style={{ cursor: 'pointer', fontWeight: 700 }} onClick={() => setPostSaveWarning('')}>×</span>
        </div>
      )}

      {/* Background PDF/WhatsApp queue status — visible to every staff role. */}
      <QueueStatus refreshKey={queueBump} />

      <h3 style={{ marginBottom: 15 }}>Collections (Contribution)</h3>
      <input placeholder="Search Contribution Data..." style={{ marginBottom: 15 }} value={search} onChange={e => setSearch(e.target.value)} />
      <div className="glass-card">
        {filtered.length === 0 && <div style={{ textAlign: 'center', padding: 20 }}>No records found.</div>}
        {filtered.map((r, i) => {
          const isResellRow = r['Is Resell'] === 'TRUE' || r['Is Resell'] === true;
          const u = isResellRow ? null : (userMap[r.Name] || { Name: 'Unknown User', Village: '-' });
          return (
            <div className="data-row" key={i}>
              <div>
                {isResellRow ? (
                  <strong style={{ display: 'block' }}>
                    ♻️ Resell: {r.Detail || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}
                  </strong>
                ) : (
                  <>
                    <strong style={{ display: 'block' }}>{u.Name} | {u.Designation || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}</strong>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{u["Father's Name"] || '-'} | {u.Village || '-'}</span>
                  </>
                )}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                {((r['Contribution Type'] ?? '').toString() || '1') === '1' ? (
                  <strong style={{ color: 'var(--success)' }}>+{fmt(r.Amount)}</strong>
                ) : (
                  <span className="badge" style={{ background: '#DBEAFE', color: '#1E40AF' }}>
                    {(r['Contribution Type'] ?? '').toString() === '2' ? 'Material' : 'Service'}{r['Certificate Or Receipt'] === 'Certificate' ? ' — Certificate' : ''}
                  </span>
                )}
                {!isResellRow && r.Detail && <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', maxWidth: 180, textAlign: 'right' }}>{r.Detail}</span>}
                {r['Payment Mode'] && <span className="badge" style={{ background: '#f3f4f6', color: '#374151' }}>{r['Payment Mode']}{paymentModeHindiOf(r['Payment Mode']) ? ` (${paymentModeHindiOf(r['Payment Mode'])})` : ''}</span>}
                {r.UTR && <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>UTR: {r.UTR}</span>}
                <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  {!isResellRow && (
                    <span
                      className="material-icons-round"
                      style={{ cursor: 'pointer', fontSize: '1.1rem', color: 'var(--primary-saffron)' }}
                      title={(r['Contribution Type'] ?? '').toString() === '2' ? 'Download Material Receipt' : r['Certificate Or Receipt'] === 'Certificate' ? 'Download Certificate' : 'Download Receipt'}
                      onClick={() => setReceiptRow(r)}
                    >
                      download
                    </span>
                  )}
                  <RowActions role={role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {editable && canAddView(role, 'home') && (
        <button className="fab" onClick={() => setShowAdd(true)}><span className="material-icons-round">add</span></button>
      )}

      <Modal open={showAdd} onClose={closeModal}>
        <h3 style={{ marginBottom: 15 }}>{editing ? 'Edit Collection' : 'Add Collection'}</h3>
        <form onSubmit={submit}>
          <div className="form-group">
            <label>Contribution Type</label>
            <select
              value={form['Contribution Type']}
              onChange={e => setForm({ ...form, 'Contribution Type': e.target.value, 'Is Resell': e.target.value === '1' ? form['Is Resell'] : false })}
            >
              <option value="1">Cash (Money)</option>
              <option value="2">Material (Item)</option>
              <option value="3">Service (Work)</option>
            </select>
          </div>

          {form['Contribution Type'] === '1' && (
            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input
                type="checkbox"
                id="isResell"
                checked={!!form['Is Resell']}
                onChange={e => setForm({ ...form, 'Is Resell': e.target.checked, Name: '' })}
                style={{ width: 'auto' }}
              />
              <label htmlFor="isResell" style={{ margin: 0 }}>This is an entry for a resold item (no contributor)</label>
            </div>
          )}

          {form['Contribution Type'] === '1' && form['Is Resell'] ? (
            <div className="form-group">
              <label>Resold Item Name</label>
              <input value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} placeholder="e.g. Old utensils, clothes, etc." />
            </div>
          ) : (
            <div className="form-group">
              <label>Contributor</label>
              <SearchableSelect
                options={userOptions}
                value={form.Name}
                onChange={id => setForm({ ...form, Name: id })}
                placeholder="Search name or village..."
                onAddNew={() => setShowQuickAdd(true)}
              />
            </div>
          )}

          {form.Name && !form['Is Resell'] && (
            <div className="form-group" style={{ background: '#f9fafb', borderRadius: 8, padding: '10px 12px' }}>
              <label style={{ marginBottom: 6 }}>Last 5 Years Contribution</label>
              {historyLoading && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Loading...</div>}
              {!historyLoading && (!history || history.length === 0) && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>No prior contributions</div>}
              {!historyLoading && history && history.map(h => {
                const tags = [];
                if (h.HasSamaan) tags.push('Material');
                if (h.HasKaam) tags.push('Service');
                return (
                  <div key={h.Year} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', padding: '3px 0' }}>
                    <span>{h.Year}</span>
                    <span>
                      {h.Amount > 0 && <strong style={{ color: 'var(--success)' }}>{fmt(h.Amount)}</strong>}
                      {tags.length > 0 && <span style={{ color: 'var(--text-muted)' }}>{h.Amount > 0 ? ' + ' : ''}{tags.join(', ')}</span>}
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {(form['Contribution Type'] === '1') ? (
            <div className="form-group">
              <label>Amount</label>
              <input type="number" value={form.Amount} onChange={e => setForm({ ...form, Amount: e.target.value })} />
            </div>
          ) : (
            <div className="form-group">
              <label>{form['Contribution Type'] === '2' ? 'What was given (Item Detail)' : 'What work was done (Work Detail)'}</label>
              <textarea rows={2} value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} style={{ width: '100%', padding: 8, borderRadius: 8, border: '1px solid #ddd' }} />
            </div>
          )}

          {form['Contribution Type'] === '3' && (
            <div className="form-group">
              <label>Document Type</label>
              <select value={form['Certificate Or Receipt']} onChange={e => setForm({ ...form, 'Certificate Or Receipt': e.target.value })}>
                <option value="Receipt">Receipt</option>
                <option value="Certificate">Certificate</option>
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (
            <div className="form-group">
              <label>Payment Mode</label>
              <select value={form['Payment Mode']} onChange={e => setForm({ ...form, 'Payment Mode': e.target.value })}>
                {paymentModeOptions.map(p => (
                  <option key={p['English Value']} value={p['English Value']}>
                    {p['English Value']}{p['Hindi Label'] ? ` (${p['Hindi Label']})` : ''}
                  </option>
                ))}
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online') && (
            <div className="form-group">
              <label>UTR / Transaction ID</label>
              <input value={form.UTR} onChange={e => setForm({ ...form, UTR: e.target.value })} placeholder="UPI/Bank UTR number" />
            </div>
          )}

          <div className="form-group">
            <label>Date</label>
            <input type="date" value={form.Date} onChange={e => setForm({ ...form, Date: e.target.value })} />
          </div>
          <button className="btn-submit" disabled={saving}>{saving ? (savingStep || 'Saving...') : 'Save'}</button>
        </form>
      </Modal>

      <QuickAddUser
        open={showQuickAdd}
        onClose={() => setShowQuickAdd(false)}
        onCreated={(id) => { onUserCreated(); setForm(f => ({ ...f, Name: id })); }}
      />

      <Suspense fallback={null}>
        <ReceiptModal
          row={receiptRow}
          year={receiptRow ? receiptRow.Year : year}
          open={!!receiptRow}
          onClose={() => setReceiptRow(null)}
          docType={
            receiptRow && receiptRow['Contribution Type'] === '2' ? 'samaan'
            : receiptRow && receiptRow['Certificate Or Receipt'] === 'Certificate' ? 'certificate'
            : 'receipt'
          }
        />
      </Suspense>
    </>
  );
}
