<script lang="ts">
  // Ported from React views/Home.jsx — budget overview + collections list for a
  // year: add/edit/delete COLLECTIONS, contributor history, auto doc generation
  // (receipt/certificate/samaan) enqueued to the background queue, resell entries.
  import { api, fmt, reportClientError } from '$lib/api';
  import { createViewData, type ViewData } from '$lib/viewData';
  import { invalidate } from '$lib/cache';
  import Modal from '$lib/components/Modal.svelte';
  import SearchableSelect from '$lib/components/SearchableSelect.svelte';
  import QuickAddUser from '$lib/components/QuickAddUser.svelte';
  import RowActions from '$lib/components/RowActions.svelte';
  import QueueStatus from '$lib/components/QueueStatus.svelte';
  import { canAddView } from '$lib/permissions';
  import { createDropdownList } from '$lib/dropdownList';
  import { isTruthyFlag } from '$lib/flags';
  import { checkMoney } from '$lib/money';
  import { personOptions } from '$lib/personOption';
  import { newUid } from '$lib/a11y/uid';
  // audit PR-40: one prefix per instance, so `for`/`id` pairs cannot collide when a
  // component is mounted more than once on a screen.
  const uid = newUid();

  interface Props {
    year: string;
    users: any[];
    onUserCreated: () => void;
    role: string;
    editable: boolean;
  }
  let { year, users, onUserCreated, role, editable }: Props = $props();

  function autoGenerateDocType(payload: any): string | null {
    if (payload['Is Resell'] === 'TRUE') return null;
    const type = payload['Contribution Type'];
    if (type === '1') return 'receipt';
    if (type === '2') return 'samaan';
    if (type === '3') return payload['Certificate Or Receipt'] === 'Certificate' ? 'certificate' : 'receipt_work';
    return null;
  }

  const RENDER_CAP = 300;
  const BLANK = () => ({
    Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
    Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
    Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false
  });

  // Year-scoped home view.
  // audit PR-40: deliberate one-time capture. This is EDITABLE local state seeded from a
  // prop; making it `$derived` would discard whatever the operator has typed every time the
  // parent re-rendered. The prop is re-read where it genuinely needs to be (see the $effect).
  // svelte-ignore state_referenced_locally
  let view = $state<ViewData<any>>(createViewData(`home:${year}`, () => api.getHome(year)));
  // audit PR-40: deliberate one-time capture. This is EDITABLE local state seeded from a
  // prop; making it `$derived` would discard whatever the operator has typed every time the
  // parent re-rendered. The prop is re-read where it genuinely needs to be (see the $effect).
  // svelte-ignore state_referenced_locally
  let lastYear = year;
  $effect(() => {
    if (year !== lastYear) {
      lastYear = year;
      view = createViewData(`home:${year}`, () => api.getHome(year));
    }
  });
  let vs = $state({ data: undefined as any, loading: true, error: '' });
  $effect(() => view.subscribe((v) => (vs = v as any)));

  const paymentModeList = createDropdownList('Payment Mode');
  let paymentModeOptions = $state<any[]>([]);
  $effect(() => paymentModeList.subscribe((s) => (paymentModeOptions = s.options)));
  const paymentModeHindiOf = (v: string) => paymentModeList.hindiOf(v);

  let search = $state('');
  let showAdd = $state(false);
  let showQuickAdd = $state(false);
  let form = $state<any>(BLANK());
  let saving = $state(false);
  let savingStep = $state('');
  let postSaveWarning = $state('');
  let queueBump = $state(0);
  let editing = $state<any>(null);
  let history = $state<any[] | null>(null);
  let historyLoading = $state(false);

  let userMap = $derived.by(() => {
    const m: Record<string, any> = {};
    (users || []).forEach((u) => (m[u.ID] = u));
    return m;
  });
  // Name + father's name, so two same-name people in one village are distinguishable — and
  // searchable by either (see lib/personOption.ts).
  let userOptions = $derived(personOptions(users));

  // Contribution history for the selected contributor (matches deps [form.Name]).
  let lastHistName = '__init__';
  $effect(() => {
    const name = form.Name;
    if (name === lastHistName) return;
    lastHistName = name;
    if (!name) { history = null; return; }
    historyLoading = true;
    api.getUserHistory(name)
      .then((h: any) => (history = h))
      .catch(() => (history = null))
      .finally(() => (historyLoading = false));
  });

  let filtered = $derived.by(() => {
    const q = search.toLowerCase();
    return (vs.data?.collections || []).filter((r: any) => {
      if (isTruthyFlag(r['Is Resell'])) return (r.Detail || '').toLowerCase().includes(q);
      const u = userMap[r.Name] || { Name: 'Unknown User' };
      return (u.Name || '').toLowerCase().includes(q);
    });
  });
  let visible = $derived(filtered.slice(0, RENDER_CAP));

  // FEAT-003: the browser no longer fills the .docx or builds the QR for the auto
  // path — that moved server-side (Render). The old fillDocxForQueue (which imported
  // $lib/docxFill + $lib/qrCode and called getDocxTemplateForDoc / getReceiptData) is
  // gone, so this bundle no longer pulls docxtemplater/qrcode for the auto path.

  async function submit(e: Event) {
    e.preventDefault();
    const isMoney = form['Contribution Type'] === '1';
    const isResell = isMoney && !!form['Is Resell'];
    const isUtrMode = isMoney && !isResell && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online');
    if (isResell) {
      if (!form.Detail.trim()) { alert("Resold item's name is required"); return; }
    } else {
      if (!form.Name) { alert('Please select a contributor'); return; }
      if (!isMoney && !form.Detail.trim()) { alert('Detail is required (what was given / what work was done)'); return; }
    }
    // audit P0-09: this used to be `if (!form.Amount)` only, so -500 / 1e21 /
    // '12.3456' were sent to the API. Same rules as the backend (lib/money.ts).
    if (isMoney || isResell) {
      const amount = checkMoney(form.Amount, 'Amount');
      if (!amount.ok) { alert(amount.message); return; }
    }
    saving = true;
    try {
      const payload: any = {
        Name: isResell ? '' : form.Name,
        'Payment Mode': isMoney ? form['Payment Mode'] : '',
        UTR: isUtrMode ? form.UTR : '',
        Date: form.Date,
        'Contribution Type': form['Contribution Type'],
        Amount: (isMoney || isResell) ? form.Amount : '',
        Detail: (isMoney && !isResell) ? '' : form.Detail,
        'Certificate Or Receipt': form['Contribution Type'] === '3' ? form['Certificate Or Receipt'] : '',
        'Is Resell': isResell ? 'TRUE' : 'FALSE'
      };
      let savedRowIndex: number;
      let genYear: any;
      const isNewEntry = !editing;
      if (editing) {
        genYear = editing.Year;
        savedRowIndex = editing.__rowIndex;
        // `Sl. No.` and `Created By` are NOT sent. The server owns both — the receipt
        // number and who recorded the entry — and since #323 it REJECTS them, which is
        // what broke every edit on this screen. Leaving them out is safe as well as
        // required: updateRecord builds `SET` from the keys it receives, so a column that
        // is not sent keeps its stored value.
        await api.updateRecord('COLLECTIONS', editing.__rowIndex, { Year: editing.Year, ...payload });
      } else {
        genYear = year === 'All' ? new Date().getFullYear() : year;
        const res: any = await api.saveRecord('COLLECTIONS', { Year: genYear, ...payload });
        savedRowIndex = res.rowIndex;
      }
      invalidate('home:');

      const docType = autoGenerateDocType(payload);
      const warnings: string[] = [];

      // FEAT-003: enqueue REFERENCES ONLY. The server derives the recordId +
      // payload from the stored row (audit P0-03), resolves the template,
      // dispatches the fill + QR + PDF to Render, and on the callback writes the
      // index and sends WhatsApp then email in that order.
      savingStep = 'Adding to the queue...';
      try {
        await api.enqueueCollectionJob({
          docType: docType || '',
          year: genYear,
          rowIndex: savedRowIndex,
          isNewEntry
        });
        api.processCollectionQueue().catch(() => {});
        warnings.push('The document and WhatsApp message have been queued in the background — they will complete shortly.');
      } catch (err) {
        reportClientError('Home', 'enqueueCollectionJob failed', err as Error, { docType, genYear, rowIndex: savedRowIndex });
        // The entry was saved; only the background queue failed. There is no
        // in-browser fallback any more (the fill is server-side) — surface it so
        // the operator can retry from the Queue Monitor.
        warnings.push('The entry was saved, but queuing the document/message failed: ' + (err as Error).message
          + ' A Superadmin can retry it from the Queue Monitor.');
      }

      postSaveWarning = warnings.join(' | ');
      queueBump = queueBump + 1;
      closeModal();
      view.refresh();
    } catch (err) {
      alert((err as Error).message);
    } finally {
      saving = false;
      savingStep = '';
    }
  }

  function closeModal() {
    showAdd = false;
    editing = null;
    form = BLANK();
  }

  function openEdit(r: any) {
    editing = r;
    form = {
      Name: r.Name, Amount: r.Amount, 'Payment Mode': r['Payment Mode'] || 'Cash', UTR: r.UTR || '',
      Date: r.Date || new Date().toISOString().slice(0, 10),
      'Contribution Type': (r['Contribution Type'] ?? '').toString() || '1', Detail: r.Detail || '',
      'Certificate Or Receipt': r['Certificate Or Receipt'] || 'Receipt',
      'Is Resell': r['Is Resell'] === 'TRUE' || r['Is Resell'] === true
    };
    showAdd = true;
  }

  async function remove(r: any) {
    if (!confirm('Delete this collection entry?')) return;
    try {
      await api.deleteRecord('COLLECTIONS', r.__rowIndex);
      invalidate('home:');
      view.refresh();
    } catch (err) {
      alert((err as Error).message);
    }
  }

  function historyTags(h: any): string[] {
    const tags: string[] = [];
    if (h.HasSamaan) tags.push('Material');
    if (h.HasKaam) tags.push('Service');
    return tags;
  }
</script>

{#if vs.loading}
  <div class="inline-spinner">Loading budget...</div>
{:else if vs.error}
  <div role="alert" class="error-banner">{vs.error}</div>
{:else if !vs.data}
  <div class="inline-spinner">Loading budget...</div>
{:else}
  {@const data = vs.data}
  <div class="glass-card budget-card">
    <h2 style="margin-bottom:15px;">{year === 'All' ? 'Lifetime' : year} Budget Overview</h2>
    <div style="display:flex; justify-content:space-between; margin-bottom:10px;">
      <span>(+) Past Loan Returned</span><strong>{fmt(data.pastRet)}</strong>
    </div>
    <div style="display:flex; justify-content:space-between; margin-bottom:15px;">
      <span>(+) Collection</span><strong style="color:#34D399;">+{fmt(data.totCol)}</strong>
    </div>
    <div style="border-top:1px dashed #4B5563; padding-top:15px; display:flex; justify-content:space-between;">
      <strong>TOTAL BUDGET</strong><strong style="color:var(--primary-saffron); font-size:1.5rem;">{fmt(data.totBudget)}</strong>
    </div>
  </div>

  <div class="grid-2" style="margin-bottom:20px;">
    <div class="stat-box" style="border-color:var(--danger);">
      <div style="font-size:0.8rem; color:gray;">Total Expense</div>
      <div style="font-size:1.2rem; font-weight:bold; color:var(--danger);">{fmt(data.totExp)}</div>
    </div>
    <div class="stat-box" style="border-color:var(--success);">
      <div style="font-size:0.8rem; color:gray;">Net Surplus</div>
      <div style="font-size:1.2rem; font-weight:bold; color:var(--success);">{fmt(data.surplus)}</div>
    </div>
  </div>

  {#if postSaveWarning}
    <div style="background:#FEF3C7; color:#92400E; border-radius:8px; padding:10px 12px; font-size:0.85rem; margin-bottom:12px; display:flex; justify-content:space-between; gap:8px;">
      <span>⚠️ The entry was saved, but: {postSaveWarning}</span>
      <button type="button" class="btn-bare" style="font-weight:700;"
        aria-label="Dismiss this warning" onclick={() => (postSaveWarning = '')}>×</button>
    </div>
  {/if}

  <QueueStatus refreshKey={queueBump} />

  <h3 style="margin-bottom:15px;">Collections (Contribution)</h3>
  <input placeholder="Search Contribution Data..." style="margin-bottom:15px;" bind:value={search} />

  {#if data.hasMore}
    <div style="background:#EFF6FF; color:#1E40AF; border-radius:8px; padding:8px 12px; font-size:0.85rem; margin-bottom:12px;">
      Showing the {data.shownRows} most recent of {data.totalRows} contributions.
      The totals above cover all of them. Select a specific year to see its complete list.
    </div>
  {/if}
  <div class="glass-card">
    {#if filtered.length === 0}
      <div style="text-align:center; padding:20px;">No records found.</div>
    {/if}
    {#each visible as r (r.__rowIndex)}
      {@const isResellRow = r['Is Resell'] === 'TRUE' || r['Is Resell'] === true}
      {@const u = isResellRow ? null : (userMap[r.Name] || { Name: 'Unknown User', Village: '-' })}
      {@const ctype = (r['Contribution Type'] ?? '').toString() || '1'}
      <div class="data-row">
        <div>
          {#if isResellRow}
            <strong style="display:block;">
              ♻️ Resell: {r.Detail || '-'} {#if year === 'All'}<span style="color:var(--primary-saffron); font-size:0.75rem;">[{r.Year}]</span>{/if}
            </strong>
          {:else}
            <strong style="display:block;">{u!.Name} | {u!.Designation || '-'} {#if year === 'All'}<span style="color:var(--primary-saffron); font-size:0.75rem;">[{r.Year}]</span>{/if}</strong>
            <span style="font-size:0.8rem; color:var(--text-muted);">{u!["Father's Name"] || '-'} | {u!.Village || '-'}</span>
          {/if}
        </div>
        <div style="display:flex; flex-direction:column; align-items:flex-end; gap:4px;">
          {#if ctype === '1'}
            <strong style="color:var(--success);">+{fmt(r.Amount)}</strong>
          {:else}
            <span class="badge" style="background:#DBEAFE; color:#1E40AF;">
              {ctype === '2' ? 'Material' : 'Service'}{r['Certificate Or Receipt'] === 'Certificate' ? ' — Certificate' : ''}
            </span>
          {/if}
          {#if !isResellRow && r.Detail}<span style="font-size:0.75rem; color:var(--text-muted); max-width:180px; text-align:right;">{r.Detail}</span>{/if}
          {#if r['Payment Mode']}<span class="badge" style="background:#f3f4f6; color:#374151;">{r['Payment Mode']}{paymentModeHindiOf(r['Payment Mode']) ? ` (${paymentModeHindiOf(r['Payment Mode'])})` : ''}</span>{/if}
          {#if r.UTR}<span style="font-size:0.7rem; color:var(--text-muted);">UTR: {r.UTR}</span>{/if}
          <div style="display:flex; align-items:center; gap:6px;">
            <RowActions {role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
          </div>
        </div>
      </div>
    {/each}
    {#if filtered.length > RENDER_CAP}
      <div style="text-align:center; padding:14px; color:var(--text-muted); font-size:0.85rem;">
        Showing {RENDER_CAP} of {filtered.length} matching rows — refine the search to narrow the list.
      </div>
    {/if}
  </div>

  {#if editable && canAddView(role, 'home')}
    <button class="fab" onclick={() => (showAdd = true)}><span class="material-icons-round">add</span></button>
  {/if}

  <Modal open={showAdd} onClose={closeModal} labelledBy="dlg-home-407-title">
    <h3 id="dlg-home-407-title" style="margin-bottom:15px;">{editing ? 'Edit Collection' : 'Add Collection'}</h3>
    <form onsubmit={submit}>
      <div class="form-group">
        <label for={`${uid}-f1`}>Contribution Type</label>
        <select id={`${uid}-f1`}
          value={form['Contribution Type']}
          onchange={(e) => {
            const v = (e.currentTarget as HTMLSelectElement).value;
            form = { ...form, 'Contribution Type': v, 'Is Resell': v === '1' ? form['Is Resell'] : false };
          }}
        >
          <option value="1">Cash (Money)</option>
          <option value="2">Material (Item)</option>
          <option value="3">Service (Work)</option>
        </select>
      </div>

      {#if form['Contribution Type'] === '1'}
        <div class="form-group" style="display:flex; align-items:center; gap:8px;">
          <input
            type="checkbox"
            id={`${uid}-isresell`}
            checked={!!form['Is Resell']}
            onchange={(e) => (form = { ...form, 'Is Resell': (e.currentTarget as HTMLInputElement).checked, Name: '' })}
            style="width:auto;"
          />
          <label for={`${uid}-isresell`} style="margin:0;">This is an entry for a resold item (no contributor)</label>
        </div>
      {/if}

      {#if form['Contribution Type'] === '1' && form['Is Resell']}
        <div class="form-group">
          <label for={`${uid}-f2`}>Resold Item Name</label>
          <input id={`${uid}-f2`} value={form.Detail} oninput={(e) => (form = { ...form, Detail: (e.currentTarget as HTMLInputElement).value })} placeholder="e.g. Old utensils, clothes, etc." />
        </div>
      {:else}
        <div class="form-group">
          <label for={`${uid}-contributor1`}>Contributor</label>
          <SearchableSelect id={`${uid}-contributor1`}
            options={userOptions}
            value={form.Name}
            onChange={(id) => (form = { ...form, Name: id })}
            placeholder="Search name or village..."
            onAddNew={() => (showQuickAdd = true)}
          />
        </div>
      {/if}

      {#if form.Name && !form['Is Resell']}
        <div class="form-group" style="background:#f9fafb; border-radius:8px; padding:10px 12px;">
          <p class="form-label" style="margin-bottom:6px; font-weight:600;">Last 5 Years Contribution</p>
          {#if historyLoading}<div style="font-size:0.85rem; color:var(--text-muted);">Loading...</div>{/if}
          {#if !historyLoading && (!history || history.length === 0)}<div style="font-size:0.85rem; color:var(--text-muted);">No prior contributions</div>{/if}
          {#if !historyLoading && history}
            {#each history as h (h.Year)}
              {@const tags = historyTags(h)}
              <div style="display:flex; justify-content:space-between; font-size:0.85rem; padding:3px 0;">
                <span>{h.Year}</span>
                <span>
                  {#if h.Amount > 0}<strong style="color:var(--success);">{fmt(h.Amount)}</strong>{/if}
                  {#if tags.length > 0}<span style="color:var(--text-muted);">{h.Amount > 0 ? ' + ' : ''}{tags.join(', ')}</span>{/if}
                </span>
              </div>
            {/each}
          {/if}
        </div>
      {/if}

      {#if form['Contribution Type'] === '1'}
        <div class="form-group">
          <label for={`${uid}-f3`}>Amount</label>
          <input id={`${uid}-f3`} type="number" min="0.01" step="0.01" value={form.Amount} oninput={(e) => (form = { ...form, Amount: (e.currentTarget as HTMLInputElement).value })} />
        </div>
      {:else}
        <div class="form-group">
          <label for={`${uid}-f4`}>{form['Contribution Type'] === '2' ? 'What was given (Item Detail)' : 'What work was done (Work Detail)'}</label>
          <textarea id={`${uid}-f4`} rows={2} value={form.Detail} oninput={(e) => (form = { ...form, Detail: (e.currentTarget as HTMLTextAreaElement).value })} style="width:100%; padding:8px; border-radius:8px; border:1px solid #ddd;"></textarea>
        </div>
      {/if}

      {#if form['Contribution Type'] === '3'}
        <div class="form-group">
          <label for={`${uid}-f5`}>Document Type</label>
          <select id={`${uid}-f5`} value={form['Certificate Or Receipt']} onchange={(e) => (form = { ...form, 'Certificate Or Receipt': (e.currentTarget as HTMLSelectElement).value })}>
            <option value="Receipt">Receipt</option>
            <option value="Certificate">Certificate</option>
          </select>
        </div>
      {/if}

      {#if form['Contribution Type'] === '1'}
        <div class="form-group">
          <label for={`${uid}-f6`}>Payment Mode</label>
          <select id={`${uid}-f6`} value={form['Payment Mode']} onchange={(e) => (form = { ...form, 'Payment Mode': (e.currentTarget as HTMLSelectElement).value })}>
            {#each paymentModeOptions as p (p['English Value'])}
              <option value={p['English Value']}>
                {p['English Value']}{p['Hindi Label'] ? ` (${p['Hindi Label']})` : ''}
              </option>
            {/each}
          </select>
        </div>
      {/if}

      {#if form['Contribution Type'] === '1' && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online')}
        <div class="form-group">
          <label for={`${uid}-f7`}>UTR / Transaction ID</label>
          <input id={`${uid}-f7`} value={form.UTR} oninput={(e) => (form = { ...form, UTR: (e.currentTarget as HTMLInputElement).value })} placeholder="UPI/Bank UTR number" />
        </div>
      {/if}

      <div class="form-group">
        <label for={`${uid}-f8`}>Date</label>
        <input id={`${uid}-f8`} type="date" value={form.Date} oninput={(e) => (form = { ...form, Date: (e.currentTarget as HTMLInputElement).value })} />
      </div>
      <button class="btn-submit" disabled={saving}>{saving ? (savingStep || 'Saving...') : 'Save'}</button>
    </form>
  </Modal>

  <QuickAddUser
    open={showQuickAdd}
    onClose={() => (showQuickAdd = false)}
    onCreated={(id) => { onUserCreated(); form = { ...form, Name: id }; }}
  />
{/if}
