import { describe, it, expect } from 'vitest';
import { parsePortalData } from './schema';
import { computeFinancials,contributorsForYear,rankedContributors,resoldItemsForYear,contributorTags,computeSummary,availableYears,loanTotalWithInterest,decadeStats,DECADE_START_YEAR } from './derive';
import { competitionRank } from '$lib/utils/ranking'; import { localize } from '$lib/i18n'; import { pickDefaultTheme,isValidThemeId,DEFAULT_LIGHT,DEFAULT_DARK,THEMES } from '$lib/themes'; import { skinIdForTheme,THEME_SKIN_ID,DEFAULT_SKIN_ID } from '$lib/skins/skinMap';
const sample={users:[{ID:'U1',Name:'Ravi Kumar',Village:'Shaharpura'},{ID:'U2',Name:'Sanjeet Kumar',Village:'Gardih'},{ID:'U3',Name:'Abhishek Verma',Village:'Shaharpura'},{ID:'U4',Name:'Govind Verma',Village:'Gardih'},{ID:'U5',Name:'Pintu Kumar',Village:'Shaharpura'},{ID:'U6',Name:'Aarohi Bharti',Village:'Gardih'},{ID:'U7',Name:'Manish Kumar',Village:'Shaharpura'},{ID:'U8',Name:'Sunil Das',Village:'Gardih'}],collections:[{Year:2026,ID:'U1',Amount:'2100','Contribution Type':'1'},{Year:2026,ID:'U2',Amount:'2100','Contribution Type':'1'},{Year:2026,ID:'U3',Amount:'1501','Contribution Type':'1'},{Year:2026,ID:'U4',Amount:'1000','Contribution Type':'1'},{Year:2026,ID:'U5',Amount:'1000','Contribution Type':'1'},{Year:2026,ID:'U6',Amount:'786','Contribution Type':'1'},{Year:2026,ID:'U7',Amount:'500','Contribution Type':'1'},{Year:2026,ID:'U8',Amount:'600','Contribution Type':'1'},{Year:2025,ID:'U1',Amount:'999','Contribution Type':'1'}],expenses:[{Year:2026,Amount:'1503',Discription:'Decoration'}],loans:[{Year:2025,ID:'U1',Amount:'10000','Intrest Rate':'2',Tenure:'12','Loan ID':'L1'}],committee:[{Year:2026,ID:'U1','View Role':'President'}],guarantors:[],generatedFiles:[],loanConsents:[]};
describe('schema',()=>{it('parses usable portal data and tolerates unknown fields',()=>{const d=parsePortalData({...sample,extraTopLevel:1});expect(d).not.toBeNull();expect(d!.collections.length).toBe(9)});it('uses safe empty arrays for malformed sections',()=>{const d=parsePortalData({collections:'not-an-array',committee:[{Name:'x'}]});expect(d!.collections).toEqual([]);expect(d!.committee.length).toBe(1)})});
describe('financial derivations',()=>{const d=parsePortalData(sample)!;const f=computeFinancials(d,2026);it('computes collection',()=>expect(f.collection).toBe(9587));it('computes loan return',()=>expect(f.pastLoanReturned).toBe(12400));it('computes budget expense surplus',()=>{expect(f.totalBudget).toBe(21987);expect(f.totalExpense).toBe(1503);expect(f.netSurplus).toBe(20484);expect(f.available).toBe(20484)});it('clamps utilization',()=>{expect(f.utilizedPct).toBeGreaterThanOrEqual(0);expect(f.utilizedPct).toBeLessThanOrEqual(100)})});
describe('loan interest',()=>{it('computes simple interest',()=>{const r=loanTotalWithInterest({Amount:'5000','Intrest Rate':'1.5',Tenure:'10'});expect(r).toEqual({principal:5000,interest:750,total:5750})})});
describe('ranking',()=>{it('uses competition ranking',()=>expect(competitionRank([{a:10},{a:10},{a:5},{a:3},{a:3},{a:1}],x=>x.a).map(x=>x.rank)).toEqual([1,1,3,4,4,6]));it('preserves entry order and flags top five',()=>{const r=rankedContributors(parsePortalData(sample)!,2026),m=Object.fromEntries(r.map(x=>[x.item.name,x]));expect(m['Ravi Kumar'].rank).toBe(1);expect(m['Sanjeet Kumar'].rank).toBe(1);expect(m['Abhishek Verma'].rank).toBe(3);expect(m['Govind Verma'].rank).toBe(4);expect(m['Pintu Kumar'].rank).toBe(4);expect(m['Aarohi Bharti'].isTop).toBe(false);expect(r.map(x=>x.item.name)).toEqual(['Ravi Kumar','Sanjeet Kumar','Abhishek Verma','Govind Verma','Pintu Kumar','Aarohi Bharti','Manish Kumar','Sunil Das'])})});
describe('contributors',()=>{it('folds repeated contributions and preserves tags',()=>{const d=parsePortalData({users:[{ID:'A',Name:'Multi Giver'},{ID:'B',Name:'Money+Material'}],collections:[{Year:2026,ID:'A',Amount:'300','Contribution Type':'1'},{Year:2026,ID:'A',Amount:'200','Contribution Type':'1'},{Year:2026,ID:'B',Amount:'700','Contribution Type':'1'},{Year:2026,ID:'B',Amount:'0','Contribution Type':'2',Detail:'Soop'}]})!,l=contributorsForYear(d,2026),a=l.find(x=>x.name==='Multi Giver')!,b=l.find(x=>x.name==='Money+Material')!;expect(a.amount).toBe(500);expect(a.count).toBe(2);expect(contributorTags(a)).toEqual(['money']);expect(contributorTags(b)).toEqual(['money','material'])})});
describe('resell and summary',()=>{const d=parsePortalData({users:[{ID:'M',Name:'Money Person'},{ID:'X',Name:'Material Person'}],collections:[{Year:2026,ID:'M',Amount:'1000','Contribution Type':'1'},{Year:2026,ID:'X',Amount:'0','Contribution Type':'2',Detail:'Bamboo soop'},{Year:2026,Name:'Old Chair',Amount:'500','Is Resell':'TRUE'}]})!;it('excludes resell',()=>{const s=computeSummary(d,2026);expect(s.totalCollected).toBe(1000);expect(s.contributors).toBe(2)});it('surfaces resell separately',()=>{const x=resoldItemsForYear(d,2026);expect(x).toHaveLength(1);expect(x[0].name).toBe('Old Chair')})});
describe('years and decade',()=>{const d=parsePortalData(sample)!;it('returns years',()=>expect(availableYears(d)).toEqual([2026,2025]));it('uses current decade API',()=>{const s=decadeStats(d);expect(s.startYear).toBe(DECADE_START_YEAR);expect(s.years.length).toBeGreaterThan(0);expect(s.years[0].year).toBe(DECADE_START_YEAR);expect(s.years.find(y=>y.isCurrent)).toBeDefined()})});
describe('i18n and theme registry',()=>{it('localize prefers Hindi',()=>expect(localize({Name:'English','Name (Hindi)':'हिंदी'},'Name','hi')).toBe('हिंदी'));it('validates theme ids',()=>{expect(pickDefaultTheme(true)).toBe(DEFAULT_DARK);expect(pickDefaultTheme(false)).toBe(DEFAULT_LIGHT);expect(isValidThemeId('sunrise')).toBe(true);expect(isValidThemeId('does-not-exist')).toBe(false);expect(isValidThemeId('kinetic-archive')).toBe(true)})});
describe('skin registry coverage',()=>{const validSkins=new Set(['premium','classic','slate','aurora','festival','surya-ghat','kinetic-archive']);it('every gallery theme maps to a known skin',()=>{for(const theme of THEMES){expect(THEME_SKIN_ID[theme.id]).toBeDefined();expect(validSkins.has(skinIdForTheme(theme.id))).toBe(true)}});it('unknown themes fall back safely',()=>{expect(skinIdForTheme('does-not-exist')).toBe(DEFAULT_SKIN_ID);expect(skinIdForTheme(null)).toBe(DEFAULT_SKIN_ID)});it('gallery covers all seven shipped skins',()=>expect(new Set(THEMES.map(t=>skinIdForTheme(t.id))).toEqual(new Set(['premium','classic','slate','aurora','festival','surya-ghat','kinetic-archive'])))})
