<script lang="ts">
  import '../app.css';
  import { onMount } from 'svelte';
  import { fade } from 'svelte/transition';
  import { initPortal } from '$lib/stores/portal';
  import { config } from '$lib/config';
  // audit PR-45: the DEFAULT skin's Shell is a STATIC import — it is what the
  // server prerenders and what the majority of visitors hydrate, so it must not
  // cost a request. Every other skin arrives as one lazily-loaded chunk.
  import DefaultShell from '$lib/skins/premium/Shell.svelte';
  import { skinShell } from '$lib/stores/skin';
  import { themeGalleryOpen, closeThemeGallery } from '$lib/stores/ui';
  import Chatbot from '$lib/components/Chatbot.svelte';
  import AnnouncementPopup from '$lib/components/AnnouncementPopup.svelte';
  import ThemeGallery from '$lib/components/ThemeGallery.svelte';
  import Seo from '$lib/components/Seo.svelte'; // audit PR-42: per-route canonical + social + JSON-LD
  import { pwaInfo } from 'virtual:pwa-info';
  import { listenForSubscriptionChange } from '$lib/push';
  import { initInbox } from '$lib/stores/notifications';
  import { startSync } from '$lib/sync';
  import { browser } from '$app/environment';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';

  let { children } = $props();

  // Svelte 5 renders a dynamic component from a plain variable reference.
  const shell = skinShell(DefaultShell);
  let Shell = $derived($shell);

  // The <link rel="manifest"> tag string generated by @vite-pwa/sveltekit,
  // injected into <head> below so the manifest is actually linked (installable +
  // discoverable by PWABuilder/browsers). app.html also carries a static
  // fallback link for pre-hydration crawlers.
  let webManifestLink = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');

  // The QR printed on every receipt / certificate opens the portal at the ROOT
  // with `?record=<id>` (see mgmt qrCode.js publicRecordUrl). Forward those to
  // the verification page, keeping the id, so every already-printed QR works.
  $effect(() => {
    if (!browser) return;
    const rec = $page.url.searchParams.get('record');
    if (rec && $page.url.pathname !== '/verify') {
      void goto(`/verify?record=${encodeURIComponent(rec)}`, { replaceState: true });
    }
  });

  onMount(() => {
    initPortal();
    // Register the service worker (autoUpdate) so the app works offline and
    // meets PWA installability. Dynamically imported so SSR/prerender never
    // touches the browser-only virtual module.
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({ immediate: true });
    });
    // Refresh the data when connectivity returns or the tab comes back to the
    // foreground, and register the (Chromium-only) SW sync mechanisms.
    const stopSync = startSync();
    // Keep a push subscription alive if the browser rotates its keys. No-op
    // unless the visitor has opted in.
    const stopPushListener = listenForSubscriptionChange();
    // Load the notification inbox and follow new arrivals, so the Menu sheet's
    // bell badge is correct on every page without polling.
    const stopInbox = initInbox();
    return () => {
      stopSync();
      stopPushListener();
      stopInbox();
    };
  });
</script>

<Seo />

<svelte:head>
  <!-- eslint-disable-next-line svelte/no-at-html-tags — trusted build-time string -->
  {@html webManifestLink}
</svelte:head>

<!-- The active skin owns the whole portal chrome (background, header, nav,
     footer). Switching theme -> switches skin -> the entire portal re-renders,
     with a brief cross-fade so the change feels smooth (reduced-motion users
     get an instant swap via app.css's global animation/transition override).
     audit PR-45: keyed on the Shell that is ACTUALLY rendered, not on the
     selected skin id. A non-default skin now has to be fetched, so those two
     stop being the same moment: keying on the id would fade to the old shell the
     instant the theme changed and then swap again when the chunk landed. -->
{#key Shell}
  <div in:fade={{ duration: 220 }}>
    <Shell>
      {@render children()}
    </Shell>
  </div>
{/key}

<!-- Skin-agnostic overlays rendered once, above every skin. -->
<Chatbot />
<AnnouncementPopup />
<ThemeGallery open={$themeGalleryOpen} onclose={closeThemeGallery} />
