<script lang="ts">
  import '../app.css';
  import { onMount } from 'svelte';
  import { fade } from 'svelte/transition';
  import { initPortal } from '$lib/stores/portal';
  import { config } from '$lib/config';
  import { activeSkin } from '$lib/stores/skin';
  import { themeGalleryOpen, closeThemeGallery } from '$lib/stores/ui';
  import Chatbot from '$lib/components/Chatbot.svelte';
  import AnnouncementPopup from '$lib/components/AnnouncementPopup.svelte';
  import ThemeGallery from '$lib/components/ThemeGallery.svelte';
  import { pwaInfo } from 'virtual:pwa-info';
  import { listenForSubscriptionChange } from '$lib/push';
  import { browser } from '$app/environment';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';

  let { children } = $props();

  // Svelte 5 renders a dynamic component from a plain variable reference.
  let Shell = $derived($activeSkin.Shell);

  // The <link rel="manifest"> tag string generated by @vite-pwa/sveltekit,
  // injected into <head> below so the manifest is actually linked (installable +
  // discoverable by PWABuilder/browsers). app.html also carries a static
  // fallback link for pre-hydration crawlers.
  let webManifestLink = $derived(pwaInfo ? pwaInfo.webManifest.linkTag : '');

  // The QR printed on every receipt / certificate opens the portal at the ROOT
  // with `?record=<id>` (see mgmt qrCode.js publicRecordUrl). Forward those to
  // the verification page, keeping the id, so every already-printed QR works.
  $effect(() => {
    if (!browser) return;
    const rec = $page.url.searchParams.get('record');
    if (rec && $page.url.pathname !== '/verify') {
      void goto(`/verify?record=${encodeURIComponent(rec)}`, { replaceState: true });
    }
  });

  onMount(() => {
    initPortal();
    // Register the service worker (autoUpdate) so the app works offline and
    // meets PWA installability. Dynamically imported so SSR/prerender never
    // touches the browser-only virtual module.
    import('virtual:pwa-register').then(({ registerSW }) => {
      registerSW({ immediate: true });
    });
    // Keep a push subscription alive if the browser rotates its keys. No-op
    // unless the visitor has opted in.
    return listenForSubscriptionChange();
  });
</script>

<svelte:head>
  <link rel="canonical" href={config.siteUrl} />
  <!-- eslint-disable-next-line svelte/no-at-html-tags — trusted build-time string -->
  {@html webManifestLink}
</svelte:head>

<!-- The active skin owns the whole portal chrome (background, header, nav,
     footer). Switching theme -> switches skin -> the entire portal re-renders,
     with a brief cross-fade so the change feels smooth (reduced-motion users
     get an instant swap via app.css's global animation/transition override). -->
{#key $activeSkin.id}
  <div in:fade={{ duration: 220 }}>
    <Shell>
      {@render children()}
    </Shell>
  </div>
{/key}

<!-- Skin-agnostic overlays rendered once, above every skin. -->
<Chatbot />
<AnnouncementPopup />
<ThemeGallery open={$themeGalleryOpen} onclose={closeThemeGallery} />
