<script lang="ts">
  import { FileText } from '@lucide/svelte';
  import PageHeading from '$lib/components/PageHeading.svelte';
  import { tr } from '$lib/stores/lang';
</script>

<svelte:head>
  <title>Terms — {$tr('app_title')}</title>
</svelte:head>

<PageHeading icon={FileText} titleKey="app_subtitle" subtitle="Terms of Use" />

<article class="surface space-y-3 p-5 text-sm leading-relaxed text-slate-700 dark:text-slate-300">
  <p>
    This site is provided by {$tr('org_name')} for community transparency. The information is presented in good
    faith and is derived from the committee's records.
  </p>
  <h2 class="text-base font-bold text-slate-900 dark:text-white">Use of information</h2>
  <p>
    Records are for informational and verification purposes. While the committee strives for accuracy, figures
    may be updated as records are finalised. The live financial figures are computed from published data.
  </p>
  <h2 class="text-base font-bold text-slate-900 dark:text-white">Documents</h2>
  <p>
    Downloadable receipts and certificates are generated by the committee. If a document shows as “Not Available”,
    it has not yet been published for that record.
  </p>
  <p>Seva Hi Sanskriti Hai.</p>
</article>
