<script lang="ts">
 import { portalState } from '$lib/stores/portal'; import { tr } from '$lib/stores/lang'; import { donationSettings } from '$lib/api/derive'; import { safeUrl } from '$lib/utils/format'; import { HeartHandshake, Copy } from '@lucide/svelte';
 let d=$derived(donationSettings($portalState.data));
 async function copy(v:string){if(v)try{await navigator.clipboard.writeText(v)}catch{}}
</script>
<svelte:head><title>{$tr('donate_title')} — {$tr('app_title')}</title></svelte:head>
<div class="kinetic-command"><div class="kinetic-kicker">07 / SUPPORT THE FESTIVAL</div><h1 class="kinetic-title">Donate.</h1></div><p class="kinetic-subtitle">{$tr('donate_intro')}</p>
<div class="kinetic-grid kinetic-grid--2"><section class="kinetic-panel kinetic-panel--yellow"><HeartHandshake/><div class="kinetic-label">UPI</div>{#if d.upiId}<div class="kinetic-code" style="margin-top:12px">{d.upiId}</div><button class="kinetic-button" style="margin-top:10px" type="button" onclick={()=>copy(d.upiId)}><Copy/> COPY UPI</button>{:else}<p>{$tr('donate_empty')}</p>{/if}</section><section class="kinetic-panel">{#if d.qrUrl}<img class="kinetic-qr" src={safeUrl(d.qrUrl)} alt="UPI QR"/>{:else}<div class="kinetic-label">UPI QR</div><p class="kinetic-micro">{$tr('donate_qr_unavailable')}</p>{/if}</section></div>
{#if d.bankAccountName||d.bankName||d.accountNumber||d.ifsc}<section class="kinetic-panel" style="margin-top:14px"><div class="kinetic-kicker">BANK TRANSFER</div><div class="kinetic-grid kinetic-grid--2" style="margin-top:12px"><div><div class="kinetic-label">{$tr('donate_bank_account_name')}</div><strong>{d.bankAccountName||'—'}</strong></div><div><div class="kinetic-label">{$tr('donate_bank_name')}</div><strong>{d.bankName||'—'}</strong></div><div><div class="kinetic-label">{$tr('donate_bank_account_number')}</div><strong>{d.accountNumber||'—'}</strong></div><div><div class="kinetic-label">{$tr('donate_bank_ifsc')}</div><strong>{d.ifsc||'—'}</strong></div></div></section>{/if}
