/// <reference types="vitest" />
import { sveltekit } from '@sveltejs/kit/vite';
import { SvelteKitPWA } from '@vite-pwa/sveltekit';
import { defineConfig } from 'vite';

// PWA: app-shell offline support. Static assets are precached; the portal API
// (Cloudflare Worker) uses NetworkFirst so visitors always get fresh data when
// online but still see a usable shell + last-good data when offline.
export default defineConfig({
  plugins: [
    sveltekit(),
    SvelteKitPWA({
      registerType: 'autoUpdate',
      manifest: {
        id: '/',
        name: 'Navyuvak Chhath Puja Samiti',
        short_name: 'Chhath Puja',
        description:
          'Navyuvak Chhath Puja Samiti, Shaharpura — a read-only public transparency portal: every contribution, expense, loan and committee record, live and accountable. Faith • Unity • Transparency.',
        lang: 'en',
        dir: 'ltr',
        categories: ['finance', 'social', 'utilities'],
        theme_color: '#F27A1A',
        background_color: '#0b1020',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        scope: '/',
        // Display fallback chain: prefer standalone, then minimal-ui, then browser.
        display_override: ['standalone', 'minimal-ui'],
        // Single-instance: re-open focuses/navigates the existing window.
        launch_handler: { client_mode: 'navigate-existing' },
        // No native companion app — always prefer the web app itself.
        prefer_related_applications: false,
        related_applications: [],
        // Microsoft Edge side-panel support (a narrow read-only dashboard fits well).
        edge_side_panel: { preferred_width: 400 },
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
        ],
        // App-listing preview images (wide = desktop, narrow = mobile). Branded
        // placeholders generated by scripts/gen-screenshots.mjs; swap for real
        // product screenshots anytime without a code change.
        screenshots: [
          {
            src: '/screenshots/wide.png',
            sizes: '1280x720',
            type: 'image/png',
            form_factor: 'wide',
            label: 'Navyuvak Chhath Puja Samiti — transparency portal'
          },
          {
            src: '/screenshots/narrow.png',
            sizes: '720x1280',
            type: 'image/png',
            form_factor: 'narrow',
            label: 'Navyuvak Chhath Puja Samiti — transparency portal'
          }
        ],
        shortcuts: [
          { name: 'Expenses', short_name: 'Expenses', description: 'View expense records', url: '/expenses' },
          { name: 'Loans', short_name: 'Loans', description: 'View surplus loans and guarantors', url: '/loans' },
          { name: 'Committee', short_name: 'Committee', description: 'View the committee members', url: '/committee' },
          { name: 'Downloads', short_name: 'Downloads', description: 'Find receipts and certificates', url: '/downloads' },
          { name: 'Donate Now', short_name: 'Donate', description: 'How to contribute', url: '/donate' }
        ]
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,webp,avif,woff2}'],
        runtimeCaching: [
          {
            // Portal API: prefer network, fall back to cache when offline.
            // Scoped to the API WORKER host only. It used to match /shaharpura\.com/,
            // which also matched files-chhath.shaharpura.com (the R2 file domain) —
            // so every profile photo / donation QR was pushed through this
            // NetworkFirst "api" cache. Those are cross-origin images with no CORS
            // headers, so the SW sees an opaque (status 0) response that workbox
            // will not cache; combined with networkTimeoutSeconds the request fell
            // back to an empty cache and the image failed to load. R2 files are
            // handled by their own image rule below.
            urlPattern: ({ url }) =>
              /(^|\.)workers\.dev$/.test(url.host) ||
              url.host === 'chhath-public-worker.shaharpura.com',
            handler: 'NetworkFirst',
            options: {
              cacheName: 'chhath-api',
              networkTimeoutSeconds: 6,
              expiration: { maxEntries: 32, maxAgeSeconds: 60 * 60 * 24 }
            }
          },
          // NOTE — deliberately NO runtimeCaching rule for the uploaded images
          // (R2 profile photos / donation QR on files-chhath.shaharpura.com, and
          // the Google-hosted popup images). Those hosts send NO CORS headers, so
          // when the service worker re-fetches them through a workbox strategy the
          // response is unusable and the image breaks — the classic "loads on the
          // first visit, disappears after a reload" symptom, because the SW only
          // takes control from the second load onwards. With no matching route,
          // workbox lets the request go straight to the network, exactly as it did
          // before the SW existed, so the images always load. (Trade-off: uploaded
          // images are not available offline; correctness wins.)
          {
            urlPattern: ({ url }) => /fonts\.(googleapis|gstatic)\.com/.test(url.host),
            handler: 'CacheFirst',
            options: {
              cacheName: 'chhath-fonts',
              expiration: { maxEntries: 16, maxAgeSeconds: 60 * 60 * 24 * 365 }
            }
          }
        ]
      }
    })
  ],
  test: {
    environment: 'node',
    include: ['src/**/*.{test,spec}.{js,ts}']
  }
});
